### ISSUE TITLE
CDataTable not updating properly

### ISSUE THREAD

**Issue by moejetz** [coreui/coreui-vue#105]
Hi!
I stumbled upon a bug where the CDataTable does not reflect changes in the given items array properly. This is due to the check in the watched properties of CDataTable:

```
watch: {
    ...,
    items (val, oldVal) {
      if (val && oldVal && this.objectsAreIdentical(val, oldVal)) {
        return
      }
      this.passedItems = val || []
    },
    ...
}
```

Without the check, it is always reflecting the changes correct.
In the current state, the changes are reflected rarely sometimes.

So my proposal is to disable the check:

```
watch: {
    ...,
    items (val, oldVal) {
      this.passedItems = val || []
    },
    ...
}
```

OS: Mac OS X 10.15.2
Vue.js: 2.6.11
CoreUI: 3.2.2
CoreUI-Vue: 3.0.12
Browser: Chrome 83.0.4103.106

**Comment by woothu** [comment]
Can you deliver an example on code sandbox? (You can fork this sandbox https://codesandbox.io/s/editable-columns-cdatatable-bjxiz?file=/src/App.vue) Updating items should work well (I don't remember anybody raised an issue about that)

Your solutions work perfectly but causes unneeded recalculations (change of items trigger filtering, sorting, etc.) So it is vital to avoid such simplification.

**Comment by moejetz** [comment]
Uhm, seems I cannot reproduce this in sandbox. I have a slightly more complex setup that cannot be tested as-is in the sandbox.
However, in my local testing it seems that `items` and `passedItems` diverge from each other - while `items` is always in sync, `passedItems` is not which prevents my table from updating. And `this.objectsAreIdentical(val, oldVal)` always returns true.

So I'm fine with some recalculations as long as it works as expected. The code seems to work properly in the sandbox too so if no one else encountered this problem I think it should be fine.
Anyway, thanks for your help!

**Comment by woothu** [comment]
Are you sure about that? You can import package from @coreui/vue/src and `console.log` inside `objectsAreIdentical` function. Please try this and let me know about the logs.

The log could be something like:
`console.log(JSON.stringify(obj1),  JSON.stringify(obj2), obj1.length === obj2.length, JSON.stringify(obj1) === JSON.stringify(obj2))`

**Comment by moejetz** [comment]
As you can see in the screenshot, the two strings are the same so the method returns true and the new value is not set.
But `items[0][1]` has a different value than `passedItems[0][1]`.


![WhatsApp Image 2020-06-25 at 19 54 31](https://user-images.githubusercontent.com/7048586/85773527-3ab40680-b71e-11ea-90b1-d9cd064db952.jpeg)

**Comment by woothu** [comment]
In your logs items are indeed identical, maybe this is some side effect caused by passing items multiple times. In log, items are compared correctly.
