### ISSUE TITLE
CDataTable and CPagination

### ISSUE THREAD

**Issue by princeivankent** [coreui/coreui-vue#107]
Hi I'm new to Vue CoreUI template. And now I'm stuck on implementing external pagination which is CPagination. 

The documentation says it could be use if you need to customize your pagination. 
My question is, how can I integrate the datas needed from CDataTable to pagination? 

Thanks!

**Comment by woothu** [comment]
It would be something like:

```
    <CDataTable
      :items="items"
      :fields="['username', 'registered', 'role', 'status']"
      :items-per-page="5"
     :active-page="activePage"
      hover
    />
    <CPagination :pages="Math.ceil(items.length/5)" :active-page.sync="activePage"/>
```

P.S. if you want to just realign pagination you can use `align` prop in CPagination. (you can set it also in CDataTable)
