### ISSUE TITLE
CRenderFunction in CSidebar not rerender

### ISSUE THREAD

**Issue by ThanhSonITNIC** [coreui/coreui-vue#109]
- Operating system and version: Windows 10
- Browser and version: MS Edge

When RFKey key was changed, it only append to CSidebar and it not rerender component.
Ex: when you re-login(not reload) then it will duplicate the nav items.

**Comment by woothu** [comment]
Please provide the repro (you can fork https://codesandbox.io/s/coreui-vue-dynamic-sidebar-gurry?file=/src/App.vue)
