### ISSUE TITLE
CDataTable not working with column-filter. 

### ISSUE THREAD

**Issue by Chanty-SOK** [coreui/coreui-vue#110]
Currently, I'm implementing with column filter with date range.  But, the UI from startDate and endDate doesn't appear.
[Here is the link to my code](https://codepen.io/chanty-sok/pen/PoZVMyE)
[I have following from this doc](https://coreui.io/vue/docs/components/table.html#custom-data-structures-and-filtering-sorting)

**Comment by woothu** [comment]
Did you copy also the 'script' section?

**Comment by Chanty-SOK** [comment]
@woothu  Yes I did.

**Comment by woothu** [comment]
I have created a sandbox with code from docs and it works: https://codesandbox.io/s/coreui-vue-custom-cdatatable-rh4vn?file=/src/App.vue
