### ISSUE TITLE
How to override CSidebarNavItem template?

### ISSUE THREAD

**Issue by eddivalen** [coreui/coreui-vue#111]
Hey @woothu,  I just updated my project to the last version of Core UI and I want to override the CSidebarNavitem template to make something like this: 
![image](https://user-images.githubusercontent.com/8193094/88335720-c4e19180-cd01-11ea-8c3d-c0411264c435.png)

I modified sidebar's template for coreUI@2.1.0 but now the templates are very different.

I just want to edit the CSidebarNavItem to make something like the image.

Can you please help me here?

**Comment by woothu** [comment]
Hi! We are glad that you upgraded to version 3!

You can use the default slot as mentioned in the docs 
https://coreui.io/vue/docs/components/sidebar.html#csidebarnavitem-api

**Comment by eddivalen** [comment]
Thanks for the answer @woothu, is there some example on how to use the default slot?

I'm using the Sidebar template from here [TheSidebar.vue](https://github.com/coreui/coreui-free-vue-admin-template/blob/master/src/containers/TheSidebar.vue)

**Comment by woothu** [comment]
In template sidebar is rendered by CRenderFunction component (check docs), you can also remove it and create normal component tree.

in /src/containers/_nav.js 

```
      {
        _name: 'CSidebarNavItem',
        _children: [
          {
            _name: 'CLink',
            to: '/dashboard',
            _children: [' Your custom Item']
          },  
        ]

      },
```

**Comment by eddivalen** [comment]
@woothu Do I have to remove the CRenderFunction component, and create the normal component tree to modify the CSidebarNavItem component?

I'm not sure if I have to import my modified component in the _nav.js file

**Comment by woothu** [comment]
No, but you can do a standard component tree if you don't want to use CRenderFunction. My example shows how to do it without refactor.

--
No, in order to use components in CRenderFunction they have to be globally registered.

**Comment by eddivalen** [comment]
Alright, the thing is that I'm using the CSidebarNavDropdown,  as I understand from your example I can add other components but I need to add logic because I get the number of products from a GraphQL query.

So maybe the best way is refactoring?
```
      {
        _name: 'CSidebarNavDropdown',
        name: 'Products',
        fontIcon: 'fa fa-pencil',
        role: 'Admin',
        badge: {
          variant: 'primary',
          text: 'products'
        },
        items: [
          {
            name: 'Pending',
            to: '/products/pending',
          },
          {
            name: 'Completed',
            to: '/products/completed',
          },
        ]
      },
```

**Comment by eddivalen** [comment]
@woothu Do you have some example on how to create it the standard component tree for the sidebar?

**Comment by woothu** [comment]
It is possible to pass any variable from the app, i.e. by moving `_nav.js` structure to `computed` property in `TheSidebar.vue`

Saying this in your situation I would migrate to the component tree (`_nav.js` was meant to simplify not to obscure)

**Comment by eddivalen** [comment]
Thanks a bunch for your help @woothu
