### ISSUE TITLE
How to use index column in CDataTable

### ISSUE THREAD

**Issue by kartikarora83** [coreui/coreui-vue#114]
Hi, just wanted to put index column in my CDataTable but was unable to find the easy way out,
Hope you can help here,

Previously, i was using vuetify for my project, in that for index column i simply put the following code .

` 
<v-data-table :headers="headers" :items="test"">
 <template v-slot:items="props">
        <td>{{ props.index + 1 }}</td>
 </template> 
</v-data-table> `

I am looking for something simple as this for CDataTable as well.

**Comment by woothu** [comment]
You can add 'index' field and fill it by '#index' slot similarly like 'show_details' column in docs example: https://coreui.io/vue/docs/components/table.html
