### ISSUE TITLE
Importing Specific Components Conveniently _and_ Efficiently, Tree Shaking Documentation

### ISSUE THREAD

**Issue by gotjoshua** [coreui/coreui-vue#116]
Not sure if this is a bug or a need for more detailed docs, but I want to share an observation and ask for advice:

If i use this import statement i get a 10MB bundle size:
```
import { CContainer, CCol, CRow} from '@coreui/vue/dist/coreui-vue.common'
```
if i change to the [suggestion for tree shaking](https://coreui.io/vue/docs/introduction/#optimization), it grows to 38MB:
```
import { CContainer, CCol, CRow} from '@coreui/vue/src'
```

Does this make sense?  
Am I doing something wrong with the /src method?  
Do I need to find each specific component within the /src tree (eg shake the tree myself)?

- Operating system and version
`Mac 10.13.6, Gridsome, coreui 3.2.2`

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
`Chrome Canary (but irrelevant)`

- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)
`I can try to make one if its really needed but I think the above code is enough`

**Comment by woothu** [comment]
This testing repo is about 45KB after gzip, whereas if you change import path to `@coreui/vue` it gets much larger
https://github.com/woothu/vue-ts-test

I suspect that your bundle is not optimized for production, maybe check your bundling configuration.

**Comment by gotjoshua** [comment]
@woothu, Thanks for your reply! 

> maybe check your bundling configuration.
I am using gridsome develop at the moment (and gridsome build is not working for some reason(s)), do you have any hints about the important bits of the bundling config?

**Comment by woothu** [comment]
I am not familiar with gridsome
