### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by rahultrivedi180** [coreui/coreui-vue#118]
![image](https://user-images.githubusercontent.com/32861078/90396350-b180d680-e0b3-11ea-9d82-acb53927bb77.png)

How do i put buttons and other components beside filter dropdown? I can not find any way to do it. Any help or suggestion would be helpful.

**Comment by woothu** [comment]
duplicate of #96

**Comment by rahultrivedi180** [comment]
![image](https://user-images.githubusercontent.com/32861078/90471372-b4bfa500-e13b-11ea-97f0-02f5593c2a05.png)

- But i want to set button beside this filter component
![image](https://user-images.githubusercontent.com/32861078/90471402-cd2fbf80-e13b-11ea-9e51-878421b248b5.png)

**Comment by woothu** [comment]
It is not available at this moment, after consideration we are planning to add such a feature in the next release.

**Comment by rahultrivedi180** [comment]
Thanks for understanding my request! : )
