### ISSUE TITLE
CPopover - components methods call inside popover content?

### ISSUE THREAD

**Issue by kebus01** [coreui/coreui-vue#125]
Hi everyone, 
is it somehow possible to have a popover with button which will fire some of the components methods?

I mean something like:
`<div v-c-popover="{
    header: 'Popover with button',
   content: '<button @click="someComponentMethod">Click</button>'
    }"
/>`

I have tried some experiments with Vue.compile but with no success.

Thanks in advance

**Comment by gabrieldw** [comment]
i have found a "bad practice" solution to this problem.

You just need to [call a vue function via js](https://stackoverflow.com/questions/55600042/how-to-access-a-vue-function-from-onclick-in-javascript)

```
<div v-c-popover="{ header: 'Popover with button', content: '<button onclick='\someComponentMethod\'>Click</button>' }" />

created() {
    window.someComponentMethod = this.someComponentMethod;
}

methods: {
   someComponentMethod() {
        //your function
   }
}
```

would be a nice solution if popovers work as components as [elementio ](https://element.eleme.io/#/es/component/popover#slot) does
