### ISSUE TITLE
CDataTable: striped style not working with #details slot

### ISSUE THREAD

**Issue by alexch1311** [coreui/coreui-vue#127]
Hi,
It seems that striped style is not working correctly on CDataTable when #details slot is used.
See example on codesandbox here: https://codesandbox.io/s/cdatatable-striped-issue-thji5

*CoreUI: 3.4.0*
*CoreUI-Vue: 3.1.4*

**Comment by slav0nic** [comment]
https://github.com/coreui/coreui-vue/issues/77

**Comment by xidedix** [comment]
thanks @alexch1311 - closed with https://github.com/coreui/coreui-vue/commit/5e4a9206aea6207e50f2ce8a80d6aeea7cb78e55
