### ISSUE TITLE
CTooltip not dynamically updating

### ISSUE THREAD

**Issue by sarah-mueller** [coreui/coreui-vue#128]
Hello,
I saw this thread where it was mentioned that the CTooltip directive is not updating dynamically:
https://github.com/coreui/coreui-vue/issues/112#issuecomment-663440632

I also observed this now in my application.

Will there be a fix for this soon?

**Comment by xidedix** [comment]
@sarah-mueller please update `@coreui/vue` to `3.1.5`

**Comment by sarah-mueller** [comment]
Thank you!
