### ISSUE TITLE
Laravel + vue3 + coreui-vue

### ISSUE THREAD

**Issue by work1120** [coreui/coreui-vue#129]
Hello!
I am doing application development with Laravel + vue3 and want to use coreui-vue

Even if I install coreui-vue on a project that supports vue3, it doesn't work.

https://github.com/coreui/coreui-free-vue-admin-template
I saw it, but it seems that I am using vue2

Is Laravel + vue3 + coreui-vue possible?

**Comment by baradhili** [comment]
vue3 with coreui-vue seems sort of possible.. 

import CoreuiVue from '@coreui/vue';
import App from './App.vue';
const app = createApp(App)
app.use(CoreuiVue)
app.mount('#app');

but there are lots of moving parts in the dashboard...  Laravel+vue+Vite can be found here.. https://github.com/hjbdev/laravel-vite-starter
