### ISSUE TITLE
How to give custom column names in CoreUI Table columns?

### ISSUE THREAD

**Issue by pverma911** [coreui/coreui-vue#131]
Title,

I have an array of objects coming in as items for the table
For e.g. [{name:'Sam',age:'24}]

I want to set custom field names like instead of column to be named as age, I want it to display column name as Id instead of age.

So, Basically how can I set custom column names?

**Comment by xidedix** [comment]
@pverma911 
See `fields` prop: https://coreui.io/vue/docs/3.0/components/table.html#cdatatable-api

**Comment by pverma911** [comment]
> @pverma911
> See `fields` prop: https://coreui.io/vue/docs/3.0/components/table.html#cdatatable-api

I didn't understand it can you pls give me an example as to how to?

**Comment by pverma911** [comment]
@xidedix Need your help buddy. 
or Anyone else?

**Comment by slav0nic** [comment]
```vue
fields: [
  { key: 'age', label: 'id'},
   ...
}
```
