### ISSUE TITLE
CDataTable sorterValue with date not working

### ISSUE THREAD

**Issue by major697** [coreui/coreui-vue#136]
I have CDataTable:
```
<CDataTable
         //..
        :items="items"
        :sorterValue="sorterValue">
        //...
</CDataTable>

computed: {
    sorterValue() {
        return {
            column: 'createdAt',
            asc: false,
        }
    },
},
```

`` I `change` in `items` from e.g.: `1612115738004` to `31/01/2021 5:55`
And this format (`31/01/2021 5:55`) not sorting correctly:
![image](https://user-images.githubusercontent.com/18541212/106596699-afbda900-6555-11eb-8cc6-702a87ba0878.png)

**Comment by xidedix** [comment]
Sorting will be performed correctly only if column values are of one type: string (case insensitive) or number.

You can workaround the issue by sorting on timestamp column instead.
See: https://codesandbox.io/s/coreui-vue-cdatatable-custom-filter-and-sort-q2ouk?file=/src/App.vue:1613-1632
