### ISSUE TITLE
CSwitch error when checked in Number

### ISSUE THREAD

**Issue by lumos94** [coreui/coreui-vue#138]
Hello,
I am getting the below error on my cswitch: 
`[Vue warn]: Invalid prop: type check failed for prop "checked". Expected Boolean, got Number with value 0.`

` <CSwitch
        class="ml-5"
        :color="enableSwitchColor"
        :checked.sync="form.status"
        variant="3d"
        shape="pill"
        type="checkbox"
        id="status"
  />`

`form.status` is always either a 1 or 0.

In the [docs ](https://coreui.io/vue/docs/components/switch.html)it says it can accept Numbers, then why is this error showing?
![image](https://user-images.githubusercontent.com/24844718/107860958-4a1dc680-6e4b-11eb-9219-b1da36e9a5ad.png)

**Comment by xidedix** [comment]
@lumos94 thanks for the catch - there is an error in the docs.
See: https://github.com/coreui/coreui-vue/blob/94bb062091ff4c7bf3d3e22de8237f3aa1640a7b/src/components/switch/CSwitch.vue#L37
