### ISSUE TITLE
CSelect multiple does not accept size attr

### ISSUE THREAD

**Issue by leonardootoni** [coreui/coreui-vue#142]
CSelect with "mutiple" does not allow to set a size.
Is there a way to set its height through a basic attr as Bootstrap Vue allow?

 "@coreui/vue": "^3.2.7"

**Comment by khackskjs** [comment]
If you wanna set height options box that dropped down when click select, you can use v-deep just like this

<CMultiSelect class="multi-select">
<style lang="scss" scoped>
.multi-select {
  &::v-deep {
    .c-multi-select-options {
      height: 500px;
    }
  }
}
