### ISSUE TITLE
Modal: closes if onmouseup event is outside of the modal

### ISSUE THREAD

**Issue by ehni** [coreui/coreui-vue#153]
Dear coreui-vue Team,

I think there might be a bug within the modal.

Before opening an issue:

- [x]  [Search for duplicate or closed issues](https://github.com/coreui/coreui-vue/issues?utf8=%E2%9C%93&q=is%3Aissue)
    - Nothing similar found
- [x]  Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
    - Can be reproduced using the example modal in the docs: https://coreui.io/vue/docs/components/modal.html
- [x] Read the [contributing guidelines](./CONTRIBUTING.md)

## What's wrong

When you open the modal and highlight some text the modal closes if the `onmouseup` event happens outside of the modal. This can lead to confusion when e.g. selecting some text.

The example modal in the official docs already show the behaviour: https://coreui.io/vue/docs/components/modal.html

<details>
  <summary>Example video</summary>

  
  ![modal_behaviour](https://user-images.githubusercontent.com/19166582/127609480-0f3fdf1b-930c-4d15-be07-43d776dd11ff.gif)
  
</details>

## Expected behaviour

When the `onmousedown` event happens inside the modal the `onmouseup` event should not close the modal, even if it happens outside of the modal.

The expected behaviour is e.g. shown in the vuematerial modal: https://vuematerial.io/components/dialog/

<details>
  <summary>Example video</summary>
  
  
![modal_expected_behaviour](https://user-images.githubusercontent.com/19166582/127609526-b98018f0-f23e-4a63-8278-e6ad735914e2.gif)  
</details>

**Comment by ehni** [comment]
There was no reaction for a few days now.

Reaching out to @xidedix. Is the modal behaviour expected? 

I prepared a PR for this with #154

**Comment by mrholek** [comment]
@ehni do you have the same problem with CoreUI v4 ?

**Comment by mrholek** [comment]
@ehmi I found a solution in the next release I will fix it.
