### ISSUE TITLE
@coreui/vue last version not match with @coreui/coreui last version

### ISSUE THREAD

**Issue by Necrometal** [coreui/coreui-vue#157]
I've checked the core of @coreui/coreui last version (4.0.1) and the style class it provide has no prefix `'c-'` like @coreui/vue last version (3.2.11) provide on his component; so the coreui style not work on @coreui/vue component.  I think this need to be fixed;
PS: sorry i don't know where to put this report ^^

**Comment by mrholek** [comment]
We're working on @coreui/vue@4 it should be available soon.
