### ISSUE TITLE
Offcanvas disables page content

### ISSUE THREAD

**Issue by tpoisson805** [coreui/coreui-vue#160]
Currently I am a CoreUI 3x user but I was previewing the docs for v4 and found the error just on the docs page.  Have not used v4 in development so I cannot verify if this issue is part of the demo only or extends further.

Upon clicking the "Toggle offcanvas" button at https://coreui.io/vue/docs/4.0/components/offcanvas.html the Offcanvas appears correctly.  However, once the offcanvas is dismissed, the following occurs:

- Entire main page section becomes read-only or a similar state.  All buttons and links no longer function.  Nothing fades like an inactive class.  But all other normal button classes (ie: on-hover, pointer:cursor, etc) and functionality is removed.
- Side menu is non-functional and non-scrollable.  Main page retains scrolling ability, side menu does not even after clicking in the area.

This bug occurs for each offcanvas demo on the page.  Clicking the 'X' to dismiss and clickOutside both trigger this bug.  Only refreshing the page resolves the issue.  Console error: "Hydration completed but contains mismatches."

My stack:
Windows 10 Pro
Chrome 94.0.4606

**Comment by mrholek** [comment]
Fixed
