### ISSUE TITLE
CoreUI v4 + Vue v3 not binding models to inputs

### ISSUE THREAD

**Issue by alexraileanu** [coreui/coreui-vue#162]
I am trying to upgrade my codebase to use the new v4 of CoreUI and v3 of Vue but I'm running into a kind-of serious bug (I believe it is a bug?). 

I have an element like:

```
<c-form-input v-model="user.email" type="email" id="email"></c-form-input>
```

The problem is that the `user.email` value is never updated, it is always empty. I looked thru the documentation and the CoreUI Admin Example and I couldn't find anything that could point me in the right direction.

I created a codepen to showcase this issue: https://codepen.io/alexraileanu/pen/VwzyJyp. You can test it by adding whatever text in the input and then pressing the button. It will show empty string as the value is never updated with the input value.

**Comment by alexraileanu** [comment]
Follow-up: I believe the fix for this is described in the migration strategy from v2 to v3: https://v3.vuejs.org/guide/migration/v-model.html#migration-strategy (the 2nd bullet-point).

**Comment by mrholek** [comment]
@alexraileanu I'm working on it, tomorrow I will publish a new version

**Comment by mrholek** [comment]
I just release v4.0.2, so everything should be ok.

**Comment by alexraileanu** [comment]
sweet, thanks @mrholek!
