### ISSUE TITLE
Issues with default values in Smart Table

### ISSUE THREAD

**Issue by alexraileanu** [coreui/coreui-vue#166]
Upgraded to v4 and I was trying to migrate CTable to CSmartTable and I ran into a couple of issues. According to the documentation, the cleaner and column filters should only appear if they are set when calling the `c-smart-table` element. However, they always appear no matter what. This is happening on v4.0.3.

Code like:

```
<template>
  <c-smart-table
    :items='items'
    :columns='columns'
  />
</template>
<script>
import { CSmartTable } from '@coreui/vue-pro';
export default {
  name: 'test',
  components: {
    CSmartTable,
  },
  data() {
    return {
      items:[
        {name: 'John Doe', registered: '2018/01/01', role: 'Guest', status: 'Pending'},
        {name: 'Samppa Nori', registered: '2018/01/01', role: 'Member', status: 'Active', _props: { color: 'primary', align: 'middle'}},
        {name: 'Estavan Lykos', registered: '2018/02/01', role: 'Staff', status: 'Banned', _cellProps: { all: { className: 'fw-semibold'}, 'name': { color: 'info' }}},
      ],
      columns: ['name', 'registered', 'role', 'status'],
    }
  }
}
</script>
```

Screenshot: 
![image](https://user-images.githubusercontent.com/2884755/140925852-1d28c46a-3b09-4fe8-9039-5bdd45f6372e.png)

Additionally, is it possible to pass only a search value to the table filter without showing the default smart table filter?

**Comment by mrholek** [comment]
I fixed the issue with the cleaner in v4.0.3.

You can pass table filter value and hide input, ex.

`
:tableFilter="false"
tableFilterValue="john"
`
