### ISSUE TITLE
CFormInput: Not emitting change event

### ISSUE THREAD

**Issue by ShaunParsons** [coreui/coreui-vue#167]
`CFormInput` is documented as emitting a `change` event: https://coreui.io/vue/docs/4.0/forms/form-control.html#cforminput

This appears to have been removed for some reason? Will this be added back in or does the documentation need updating?

https://github.com/coreui/coreui-vue/blob/8c65225fbf8515cb11df004765bb5ab9981c0281/packages/coreui-vue/src/components/form/CFormInput.ts#L113

**Comment by mrholek** [comment]
Fixed in v4.1
