### ISSUE TITLE
Pro: Export CElementCover

### ISSUE THREAD

**Issue by simlevesque** [coreui/coreui-vue#168]
Hi

Please export CElementCover just like all other components so I can import it from `@coreui/vue-pro`. I currently need to import from `@coreui/vue-pro/dist/components/element-cover/CElementCover`.

It needs to be exported in the following file: `src/components/index.ts`

Thank you.

**Comment by mrholek** [comment]
Fixed in v4.1

**Comment by simlevesque** [comment]
Thank you !
