### ISSUE TITLE
CForrmSelect: Invalid is not used

### ISSUE THREAD

**Issue by ShaunParsons** [coreui/coreui-vue#170]
`CForrmSelect` is documented as have a `invalid` property: https://coreui.io/vue/docs/4.0/forms/select.html#props

However it is not used in the render function and appears completely redundant. https://github.com/coreui/coreui-vue/blob/main/packages/coreui-vue/src/components/form/CFormSelect.ts#L89-L114

**Comment by mrholek** [comment]
I will fix it next release.

**Comment by mrholek** [comment]
Fixed in v4.1
