### ISSUE TITLE
CSmartTable column-filter

### ISSUE THREAD

**Issue by kontyente** [coreui/coreui-vue#175]
version : 4.1.0
issue: prop column-filter, even if set to false, and filter inside the columns array also filter:false, still a row exists between head and body.

**Comment by mrholek** [comment]
Did you mean `column-filter` prop ? I will try to fix all CSmartTable issues this week.

**Comment by kontyente** [comment]
you got it...  column-filter

**Comment by mrholek** [comment]
I work on this issue, I will try to fix it next release.
