### ISSUE TITLE
Cannot use "to" attribute in CLink Component

### ISSUE THREAD

**Issue by kanemotos** [coreui/coreui-vue#177]
CLink's "to" attribute seems not to be implemented.

The "to" attribute is not available for all components that inherit from CLink.

Vue version: 3.2.23
@coreui/vue version: 4.1.0

Thanks.

**Comment by mrholek** [comment]
In v4 we don't use `vue-router`. But you can add it manually and use `to` attribute

```
<router-link
  to="/about"
  custom
  v-slot="{ href, route, navigate, isActive, isExactActive }"
>
  <CLink :active="isActive" :href="href" @click="navigate"
    >{{ route.fullPath }}</NavLink
  >
</router-link>
```
