### ISSUE TITLE
Replace vue-clickaway by vue-clickaway2

### ISSUE THREAD

**Issue by guilhermeaiolfi** [coreui/coreui-vue#18]
Hi,

I had some problems with ```vue-clickaway``` and found out that the project is 'dead' since April 10th. There is a fork called ```vue-clickaway2``` that fixed some issues and added some extra functionality. 

Could you consider replacing this module?

Thanks

**Comment by woothu** [comment]
Module replaced in latest alpha version: https://github.com/coreui/coreui-vue/releases/tag/3.0.0-alpha.3
