### ISSUE TITLE
CFormSelect does not respect initially selected value

### ISSUE THREAD

**Issue by alxndrdude** [coreui/coreui-vue#182]
# Setup

```
<CFormSelect
  v-model="'2'"
  :options="[
    'Open this select menu',
    { label: 'One', value: '1' },
    { label: 'Two', value: '2', selected: true },
    { label: 'Three', value: '3', disabled: true }
  ]">
</CFormSelect>
...
data: {
  value: '2'
}
```

# Expected behavior

The option `'Two'` should be selected, if the select is rendered.
Actually, it is not.
The first entry of `options` is selected.

# Meta data
- core-ui version 4.1
- browser: Chrome, Chromium

# Suggestion
- in [CSelected](https://github.com/coreui/coreui-vue/blob/main/packages/coreui-vue/src/components/form/CFormSelect.ts#L110) a `selected` of options props could be evaluated
- I would prefer, that `v-model` should be sufficient, and `selected` in `options` is not required.

Thanks :)

**Comment by mrholek** [comment]
@alxndrdude I will fix it in the next release.

**Comment by mrholek** [comment]
Fixed
