### ISSUE TITLE
Missing CWrapper?

### ISSUE THREAD

**Issue by StrangerGithuber** [coreui/coreui-vue#187]
Hello
I am trying to use CWrapper which is in the documentation but it doesn't exists in the 4.0 version and above. Was it removed or renamed?
Because the documentation stayed at the version 3 but not updated to 4.

**Comment by mrholek** [comment]
@StrangerGithuber we replaced `CWrapper` with `<div class="wrapper d-flex flex-column min-vh-100 bg-light"></div>`, and we added those style
`.wrapper {
  width: 100%;
  @include ltr-rtl("padding-left", var(--cui-sidebar-occupy-start, 0));
  will-change: auto;
  @include transition(padding .15s);
}`
