### ISSUE TITLE
CSmartTable column filter can't be hidden and sort function stops working after items updated

### ISSUE THREAD

**Issue by sametsafak** [coreui/coreui-vue#188]
Hi, 

I have 4 feedbacks for CSmartTable component.

1- CSmartTable is not hiding column filter inputs via props or I'm using it wrong.
`:column-filter="false"` is simply does not working. I solved it via ugly css workaround.

2- If I give an empty array for items prop then update with a new array of objects that is coming from api, column sort is not working.
As a workaround, instead of defining empty array for items prop at the start, I just put an object in this array with empty values.

```
// not working
const items = []

// working
const items = [
  {
    eventTime: null,
    responseCode: null,
    responseTime: null,
    status: null,
    url: null,
  },
]
```

3- Single arrows in the pagination below of table, normally works well but if you click page 2 then click < arrow three times, table just list all of the items. Even the arrow button seems disabled, it seems it's clickable. (it is also not working with right arrow after user comes at last page)

4- For columns prop, _classes key seems not working. I can't give classes for every cell in a column. If it's not a bug, could you update the docs with an example? 

Thanks

**Comment by mrholek** [comment]
@sametsafak which version of @coreui/vue-pro do you have installed?

**Comment by dang-cb** [comment]
Hi @sametsafak what version of @coreui/vue-pro are you using? Some of these are issues that should be fixed in v4.1.4...

A couple of quick responses to the first two questions, though...

1- Not hiding column filters
This is done from the "columns" props, e.g.
```
      columns: [
        { key: 'eventTime' },
        { key: 'responseCode' },
        { key: 'responseTime' },
        {
          key: 'status',
          label: '',
          filter: false,
          sorter: false,
        },
```
...etc

2- Column filters don't work with API sourced data
This should be fixed in v4.1.4 - see #181

**Comment by sametsafak** [comment]
@mrholek I'm using 4.1.0

@dang-cb 
1- I guess column-filter-value should be updated. When I give every column `filter: false`, I still see 1 empty row instead of a row with filter inputs. My css workaround seems better for now.

`.hide-column-filter-temp {
  table thead tr:last-child {
    display: none;
  }
}`

2- It's different thing. I'm not using column filter for now. I didn't know this issue btw thanks for the information!

**Comment by mrholek** [comment]
@sametsafak I will check it and fix it in the next release. It should be ready next week

**Comment by sametsafak** [comment]
@JerryBels there is a docs page actually: https://coreui.io/vue/docs/4.1/components/smart-table.html
