### ISSUE TITLE
CSmartTable improved sorting

### ISSUE THREAD

**Issue by sametsafak** [coreui/coreui-vue#189]
Hello,

Due to different data types and languages, sorting can be difficult in tables. Therefore jQuery data tables suggests a method. Maybe it can be implemented to smart table.

**data-order attribute** 
If we use data-order attribute, table checks it first instead of value inside of td tag. It is extremely useful.
[https://stackoverflow.com/questions/17806737/custom-sorting-of-jquery-datatable-columns](https://stackoverflow.com/questions/17806737/custom-sorting-of-jquery-datatable-columns)

**Comment by mrholek** [comment]
@sametsafak I will discuss it with our team.

**Comment by wesbw** [comment]
Hi, 
What is the suggested approach on this. I couldn't see an example for sorting numbers or dates in the documentation.
https://coreui.io/react/docs/components/smart-table/#csmarttable
Thank you for your helps.

**Comment by sametsafak** [comment]
Hi @wesbw
I am sorting the array before sending it to the table. This is the only solution I have found.
