### ISSUE TITLE
CSmartTable sorterValue is not working reactively with vue 3

### ISSUE THREAD

**Issue by sametsafak** [coreui/coreui-vue#190]
Hi,

I am getting sort info from an api. Therefore I have to change sorter value dynamically after request finished.
In the CSmartTable docs, says 'use .sync modifier' but it is deprecated in vue 3. So I checked the [vue 3 migration guide](https://v3-migration.vuejs.org/breaking-changes/v-model.html#migration-strategy) and see how to use it properly.

I tried `v-model:sorterValue="mySorterValue"` but it's not working. 

I am using _@coreui/vue-pro@4.1.4_

**Comment by mrholek** [comment]
@sametsafak do you use Composition API or Options API

**Comment by mrholek** [comment]
If Composition API, please try this `const mySorterValue = reactive({ column: 'status', state: 'asc' })`

**Comment by sametsafak** [comment]
@mrholek no I am using Options API
