### ISSUE TITLE
CSmartTable _classes and _cellClasses props are not working

### ISSUE THREAD

**Issue by sametsafak** [coreui/coreui-vue#191]
Hi,

When I check the docs it says you can use  _classes and _cellClasses props to add classes to cells but It seems not implemented to CSmartTable.

My core ui version is 4.1.4

**Comment by mrholek** [comment]
@sametsafak there is a bug in our docs, you can add classes and props using
`_cellProps: { all: { className: 'fw-semibold'}, 'name': { color: 'info' }}}`

or 

`_props: { color: 'primary', align: 'middle'}}` if you want to add props or styles to tr element

**Comment by sametsafak** [comment]
@mrholek ok it's working now, thank you for updating the docs
