### ISSUE TITLE
CoreUI for Vue not working

### ISSUE THREAD

**Issue by doylestolk** [coreui/coreui-vue#199]
Hello,

I'm running Vue 3 with Typescript and I'm trying to add CoreUI to my project.
When I import a CoreUI component and try to build my project I get the following error:
Failed to compile.

./node_modules/@coreui/vue/dist/index.es.js 3831:39
Module parse failed: Unexpected token (3831:39)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|                 return;
|             }
>             if (!dropdownMenuRef.value?.contains(event.target)) {
|                 hideMenu();
|             }

Does anyone know how to resolve this?

**Comment by Blacktoviche** [comment]
I'm facing the same problem.
How did you manage to solve it please?

**Comment by doylestolk** [comment]
The installation of vue CLI that I had and used to create my new project was too old apparently. So I updated it to the newest version and created a new project and imported CoreUI and it worked without any problem. I had to delete vue CLI completely and install it again because for some reason it didn't want to update no matter what I tried.

**Comment by Blacktoviche** [comment]
Thanks I will try this

**Comment by Blacktoviche** [comment]
Cleaning project, re-install vue CLI was the solution. Thankx @doylestolk
