### ISSUE TITLE
CFormCheck type="radio", unclear docs how to use

### ISSUE THREAD

**Issue by vsirghii** [coreui/coreui-vue#204]
Hello, I'm using "@coreui/vue": "^4.1.0", and trying to work with `CFormCheck type="radio"` component. I found one issue here related to Radio button, and it was `CInputRadio ` component. But as I understand it's coreui version 3.2.0 something.
In 4.1 version docs `CFormCheck ` is not explained, it's not clear how to bind this component in vue app.
All I need is just 5 radio buttons; one should be checked based on a property value on page load; checking/unchecking should update  binded object's value respectably. How would I do this simple flow???
Note that default vue.js workflow for checkboxes
```
<input type="checkbox" id="john" value="val1" v-model="person.checkedValue">
<input type="checkbox" id="mike" value="val2" v-model="person.checkedValue">
```
doesn't work with coreui ` CFormCheck type="radio"` component.

**Comment by xidedix** [comment]
@vsirghii not sure what part of the docs is unclear?
https://coreui.io/vue/docs/forms/radio.html
