### ISSUE TITLE
v-c-tooltip and v-c-popover are not working reactively

### ISSUE THREAD

**Issue by sametsafak** [coreui/coreui-vue#215]
When I try to use v-c-tooltip with a variable that changes a while, tooltip component taking variable's first (old) value. Not the updated value i.e. with settimeout or computed.

Mac OS,
Chrome,
@coreui/vue-pro v4.3.0

```vue
<h4 v-c-tooltip="myComputedVariable">
  Hello
</h4>
```

**Comment by gfoidl** [comment]
It's not stale, just no reaction from the maintainers, so please don't close.

**Comment by sametsafak** [comment]
@gfoidl I gave up and started to use floating-vue for tooltips.

**Comment by gfoidl** [comment]
> It's not stale, just no reaction from the maintainers, so please don't close.

**Comment by sametsafak** [comment]
I am using [floating-vue](https://floating-vue.starpad.dev) instead.

**Comment by gfoidl** [comment]
Yeah, you wrote that above.

My comment is just for the stupid bot, that want's to close issues even when there was no interaction from a maintainer (I'm not one). So that bot should be turned off, or a bit more activity from maintainers would be desired.

**Comment by gfoidl** [comment]
Closing issues by the bot is not equal to resolving them. So leave it open.

**Comment by jugol-kumar** [comment]
<tr v-for="item in data" :key="qut.id">
          <td>
              <a v-c-tooltip="item.name"  :href="item.url">{{ item.url }}</a>
           </td>
   </tr>


when i will render v-c-tooltip when just working this tooltip first row. i want to show this tooltip all  iteration row. so how can i solve this problem. please help me @everyone;
