### ISSUE TITLE
CFormInput type="file" has bad types

### ISSUE THREAD

**Issue by simlevesque** [coreui/coreui-vue#222]
CFormInput accepts only v-model that are strings. But when using the file input, the type of the v-model is actually interface File from `node_modules/typescript/lib/lib.dom.d.ts` because CFormInput creates a HTMLInputElement.. I couldn't find an easy way to hide this error and it breaks CI. I'm a paid customer btw.

```
(property) modelValue?: string | undefined
Type 'File | undefined' is not assignable to type 'string | undefined'.
  Type 'File' is not assignable to type 'string'.ts(2322)
CFormInput.d.ts(243, 5): The expected type comes from property 'modelValue' which is declared here on type 'IntrinsicAttributes & Partial<{ type: string; invalid: boolean; disabled: boolean; valid: boolean; tooltipFeedback: boolean; modelValue: string; plainText: boolean; readonly: boolean; }> & Omit<...>'
```

**Comment by mrholek** [comment]
Fixed in v4.3.1

**Comment by simlevesque** [comment]
Thank you very much !! @mrholek

**Comment by mrholek** [comment]
@simlevesque you're welcome!
