### ISSUE TITLE
Binding CMultiSelect 

### ISSUE THREAD

**Issue by dkwebtec** [coreui/coreui-vue#238]
How can I bind CMultiSelect? I don't see any example. v-model doesn't work.

**Comment by lunwhl** [comment]
have u found any solution?

**Comment by DogFox** [comment]
> 

![image](https://user-images.githubusercontent.com/2357740/200483333-45fc88e3-d232-410a-91b8-829918242860.png)

I wrote a simple wrapper arround CMultiSelect and translate it to v-model

**Comment by lunwhl** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/2357740/200483333-45fc88e3-d232-410a-91b8-829918242860.png)
> 
> I wrote a simple wrapper arround CMultiSelect and translate it to v-model

thx for ur reply, i did it this way too. but i can't show the initial tag.
e.g i wanted to edit user, and user has multiple roles in this component, so tag should show initially.

**Comment by DogFox** [comment]
> > > 
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/2357740/200483333-45fc88e3-d232-410a-91b8-829918242860.png)
> > I wrote a simple wrapper arround CMultiSelect and translate it to v-model
> 
> thx for ur reply, i did it this way too. but i can't show the initial tag. e.g i wanted to edit user, and user has multiple roles in this component, so tag should show initially.

i'm not sure that clearly understand you. If you talking about initian = default values, try to look on next code
![image](https://user-images.githubusercontent.com/2357740/200485085-df77a8a5-a728-49ff-a6a1-7b08d7d7e6a7.png)

**Comment by lunwhl** [comment]
thanks brother, I understood how it works.
