### ISSUE TITLE
If I change icon property of CIcon the icon doesn't change

### ISSUE THREAD

**Issue by dkwebtec** [coreui/coreui-vue#242]
template:

`<CIcon :icon="testIcon" /> {{testIcon}}     <button @click="testIcon = 'cilMoon'">Change icon</button>`

script:

```
import { computed, ref } from "vue";
const testIcon = ref("cilSun");
```

**Comment by dkwebtec** [comment]
please, can anybody check?

**Comment by mrholek** [comment]
@dkwebtec at this moment this property is not reactive, but I will try to change it.

**Comment by kevinlester** [comment]
The icon property is not reactive as of release 4.4.3 :(  Is there a plan to make it reactive?  At the moment it seems like a bug.
