### ISSUE TITLE
Toast CToastClose empty

### ISSUE THREAD

**Issue by ElBart00** [coreui/coreui-vue#249]
The examples on https://coreui.io/vue/docs/components/toast.html are not visible.
I've tried to use CToastClose but it renders an empty html element. I've checked the example on https://coreui.io/vue/docs/components/toast.html but this seems to render a html cbutton element instead of rendering CButton component.

**Comment by mrholek** [comment]
@ElBart00 I fixed demos. Can you show me your code?
