### ISSUE TITLE
Sidebar nav items are both active with similar path names

### ISSUE THREAD

**Issue by wilderbonsai** [coreui/coreui-vue#25]
Currently sidebar navigation items will become both active if they share similar path names.

ie.
routes 
` {
          path: 'foo',
          name: 'Foo',
          component: Foo
        },
        {
          path: 'foo/bar',
          name: 'Bar',
          component: Bar
        },`

When `foo/bar` is selected, `foo` will also have an active state in the sidebar.
This becomes a hinderance when trying to do url paths like ':username/settings and /:username'

Maybe `exact` state would work, and allowing it to be added as a prop
https://github.com/vuejs/vue-router/issues/1014

**Comment by woothu** [comment]
Hi! Thank you for reporting this bug. 

This issue will be solved in version 3, where all mechanism will be refactored, and it will be possible to define the exact prop in _nav.js.

If you want to solve this before v3 release, you can pass 'exact' prop in router-link component (it is inside SidebarNavLink component, which you can find on path node_modules/@coreui/vue/src/components/Sidebar. To avoid breaking this solution after an npm update/install you can copy this component inside your template.

**Comment by xidedix** [comment]
@wilderbonsai @woothu 
see also: https://github.com/coreui/coreui-react/issues/59#issuecomment-467298501
It may be somewhat helpful
