### ISSUE TITLE
CFormCheck type="radio" with v-model not updating as expected

### ISSUE THREAD

**Issue by joel-rich** [coreui/coreui-vue#251]
Radio buttons do not reflect v-model value on load, nor do they properly update v-model when new radio is selected.

To reproduce: set up two radio buttons with values using CFormCheck

```
//in <template>
<CForm>
  <CFormCheck
    type="radio"
    name="radioExample"
    label="Yes"
    value="Yes"
    v-model="formFields.radio"
  />
  
  <CFormCheck
    type="radio"
    name="radioExample"
    label="No"
    value="No"
    v-model="formFields.radio"
  />
</CForm>
         

//in <script setup>
const formFields = reactive({
  radio: 'Yes'
})
 ```

On page load: 
![image](https://user-images.githubusercontent.com/6070705/223318212-21160c2c-5e4d-4ddb-815c-75ac10cf2d44.png)
![image](https://user-images.githubusercontent.com/6070705/223318257-3fc5e5c2-c8a3-42f4-9165-e6efa814bb6f.png)

After clicking either "Yes" or "No" radio button
Radio does not change on first click. Sets model value to "true"
![image](https://user-images.githubusercontent.com/6070705/223318331-ad141b3b-4a9d-4da5-b930-e0539938c9d0.png)
![image](https://user-images.githubusercontent.com/6070705/223318354-b67f3aae-b54e-47ac-a9ea-e22890d6a48f.png)

Subsequent clicks visually change which radio is selected, but model value stays "true" regardless which one is selected.
![image](https://user-images.githubusercontent.com/6070705/223319365-40654ca2-0b27-4c45-9322-28c7d6626be9.png)
![image](https://user-images.githubusercontent.com/6070705/223319377-9a9b1f4e-b0ae-42a1-adf9-c0e3d9f2c251.png)

It works properly if I don't use CFormCheck

```
//replace above <template> code with this and it works/updates properly
<input type="radio" id="yes" value="Yes" v-model="formFields.radio" />
<label for="yes">Yes</label>
<br />
<input type="radio" id="no" value="No" v-model="formFields.radio" />
<label for="no">No</label>
```

**Comment by joel-rich** [comment]
Has anyone had a chance to look at this?

**Comment by benf710** [comment]
Also confirming I've experienced this issue with the radio button component.

**Comment by mrholek** [comment]
It will be fixed in the next release

**Comment by joel-rich** [comment]
@mrholek Thanks! I've noticed it's fixed on the latest pre-release version that I grabbed through npm. However, the validation props still aren't working properly for radio buttons (sorry if you're aware and it's on your todo list - just wanted to bring it up in case it wasn't noticed).

**Comment by Aynhard** [comment]
Hello @mrholek, i'm really exited to see you fixed the problem when resize windows error, but when i install beta version started this problem with checkboxes. They stop return **true** when send data from them and now return **on** wich broke my backend logic. I hope soon will released a stable version with those fixes.

**Comment by mrholek** [comment]
I will fix it in the next release. It should be ready next week.

**Comment by joel-rich** [comment]
@mrholek I've checked out 4.10.0, and model binding is working well (thanks!), but the invalid prop still isn't properly reactive. Is a fix for that in the works?

**Comment by IP-Developer** [comment]
Bump!

**Comment by mrholek** [comment]
@joel-rich can you give me more information about this issue?
