### ISSUE TITLE
Two Sidebars in nav menu

### ISSUE THREAD

**Issue by Ivan-Corporation** [coreui/coreui-vue#257]
The navigation menu contains two links to the sidebar. Not terrible, but highly noticeable for any bug
![image](https://github.com/coreui/coreui-vue/assets/58357980/d8bbac2e-a312-4bf1-a0c2-9ad874ab727d)

**Comment by InoueKenta** [comment]
is this admin template problem or the core ui problem?
I'm a little confused

**Comment by Ivan-Corporation** [comment]
https://coreui.io/vue/docs/getting-started/introduction.html - This link check in components tab
![image](https://github.com/coreui/coreui-vue/assets/58357980/e76ed45b-018d-4eba-8241-cd46665ee529)
