### ISSUE TITLE
Control open state of SidebarNavDropdown

### ISSUE THREAD

**Issue by bogdibota** [coreui/coreui-vue#26]
Hello,

I would like a possibility for the `SidebarNav` to control the `open` state of the `SidebarNavDropdown`.

Usecase: when expanding / collapsing the a nav dropdown, I would like to save its state in the `localStorage` or something similar. I see this as an UX improvement for the end user if you deal with complex sidebar menus.

Implementation suggestion: maybe provide a `default` open state to the `_nav` (state on mount) and a `onChange` method to store the above state.

I can help with a PR if you want ;)

Thanks

**Comment by woothu** [comment]
Hi, thank you for your feedback. Right now we are working on version 3.0 where core layout components (including sidebar) will have complete refactor. If you submit a PR, it can possibly influence the functionality of sidebar and sidebar nav in 3.0 version. 

Regards :)

**Comment by bogdibota** [comment]
Got it ;)

If you could take this suggestion into consideration when implementing v3.0, I would appreciate it.
