### ISSUE TITLE
CFormInput type="file" localization

### ISSUE THREAD

**Issue by btseee** [coreui/coreui-vue#262]
I want add translation the "Browse" and "No file selected" text are there any method to do it ?:

`<CFormInput type="file" :ref="id" :multiple="multiple" :accept="accept" @change="previewFiles" :readonly="readonly" />`

**Comment by plundermun** [comment]
I don't think this is theme based.
Both texts are provided by the browser and the current user language.
as CFormInput with type of file only renders to :
`<input accept="*" class="form-control" type="file">`
