### ISSUE TITLE
Support for Mailto: and Tel: links for sidebar menu links

### ISSUE THREAD

**Issue by makingDigital** [coreui/coreui-vue#27]
Currently, only links with http: are counted as external links for the sidebar, but mailto: and tel: are also valid link types. Add these to computed property IsExternalLink in SidebarNavLink.vue so mailto and tel links won't have the site url added in front of these link types.

![image](https://user-images.githubusercontent.com/17121596/56175730-cc64b600-603b-11e9-8a79-ce504273439c.png)

![image](https://user-images.githubusercontent.com/17121596/56175656-84459380-603b-11e9-8ab8-1809becd6a6d.png)

![image](https://user-images.githubusercontent.com/17121596/56175948-a986d180-603c-11e9-973d-4a43449faaf6.png)

**Comment by woothu** [comment]
This issue has been resolved in alpha version:
https://github.com/coreui/coreui-vue/commit/b3d8ee7659172460276a9426f49e709d8e3c0241
Stay tuned for coreui-vue 3.0 :)
