### ISSUE TITLE
CMultiSelect is not opened if clicked on icon

### ISSUE THREAD

**Issue by alxndrdude** [coreui/coreui-vue#274]
OS: Linux
Browser: Chromium version 119.0.6045.123 & Firefox version 119.0
CoreUI Pro version: 4.11.0

This Bug can, e.g., be reproduced by navigating to the [CoreUI vue multi-select docu](https://coreui.io/vue/docs/forms/multi-select.html).
Clicking the multi-select chevron icon does **not** open the multi-select-menu.
Clicking the multi-select text-area does open the multi-select-menu.
![coreui-multiselect](https://github.com/coreui/coreui-vue/assets/28753010/20cd17bb-80ff-4223-a746-d969f0da84e6)

Expected behavior:
Clicking the multi-select chevron icon does open the multi-select-menu.

Thanks for any help.

**Comment by mrholek** [comment]
It will be fixed in v5 - https://coreui.io/vue/docs/5.0/forms/multi-select.html
