### ISSUE TITLE
COffcanvas doesn't apply custom css styles, classes, ids for css styles

### ISSUE THREAD

**Issue by giquo** [coreui/coreui-vue#278]
- Operating system and version: Windows 10 22H2
- Browser: Firefox Dev Edition 122.0b5 (64-bit); Brave v1.61.109

When trying to use custom css as the documentation suggest https://coreui.io/vue/docs/components/offcanvas.html#css-variables

```
const offcanvasCreateStyle {
'--cui-offcanvas-width': '90%',
}
<COffcanvas
    backdrop="static"
    placement="end"
    :visible="isCreateCompanyOpen"
    :style="offcanvasCreateStyle"
    @hide="
      () => {
        isCreateCompanyOpen = !isCreateCompanyOpen
      }
    "
  >
```

I see no style applied, even using class="css-class" or id="css-id" on <COffcanvas>
I even used the inspector if I found something called with those names "css-class" or id="css-id" but found nothing
Tried even other custom classes but none of them are applying.

**Comment by mrholek** [comment]
Fixed in `@coreui/vue` v4.10.2 / `@coreui/vue-pro` v4.11.3
