### ISSUE TITLE
Problem with box-shadow in CoreuUI Pro Tabs

### ISSUE THREAD

**Issue by jakubstankowski** [coreui/coreui-vue#28]
Hi,

I have problem with box shadow in CoreuUI tabs, I can't change it, i try a lot of funcionality like 
`  .tab-content{
        border: none !important;
    }
    .tab-pane:active, .tab-pane:focus, .tab-content:active, .tab-content:focus{
        box-shadow: none !important;
        border: none !important;
    }`

But still doesn't work correctly, any idea for resolve this problem ? Thanks for help 
I added a screnshot with my problem 
![Zrzut ekranu (14)](https://user-images.githubusercontent.com/36790120/57219972-05b89200-6ffa-11e9-9471-061db771b6bb.png)

**Comment by woothu** [comment]
Hi! [ Cześć! :) ]
This is the default css outline behavior. To override it just define outline i.e. div:focus{ outline: none; } or .tab-pane:focus { outline: none; }
![image](https://user-images.githubusercontent.com/32914662/57220878-436aea00-6ffd-11e9-9270-265d67a4f6dc.png)

btw. why would your tab-pane be focused?

**Comment by jakubstankowski** [comment]
It's my mistake, this was not a box shadow, but the outline behavior, thanks for help :)
