### ISSUE TITLE
The documentation for CMultiSelect seems to be outdated.

### ISSUE THREAD

**Issue by CofCat456** [coreui/coreui-vue#286]
options `label` should be corrected to `text`, right?

Please let me know if I'm wrong.

![截圖 2024-03-19 上午10 32 36](https://github.com/coreui/coreui-vue/assets/93901409/8c27da54-285f-43d8-9c54-c44a01ab73aa)

**Comment by mrholek** [comment]
@CofCat456 in version 4.x use text in 5.x label

**Comment by CofCat456** [comment]
Got it! Thank you for taking the time to reply.
