### ISSUE TITLE
Problem with onChange method in v-select

### ISSUE THREAD

**Issue by jakubstankowski** [coreui/coreui-vue#29]
Hi,

I have problem with v-select, from coreUI advanced forms. 
I would like detect change value, so i added a method @change, but it doesn't work because don't show my any changes, code: 

`<v-select id="basicSelect" @change="onChange($event)" v-model="value" :options="feedingTypeOptions"
placeholder="Select feeding type">

onChange(event) {
console.log(event.target.value);
            console.log('its change!@#!@#!@#123');
        },`

Thanks for help !

**Comment by woothu** [comment]
Hi! 
Try watching on @input event.

v-select component docs:
https://vue-select.org/api/events.html#option-created

**Comment by jakubstankowski** [comment]
Still don't work correct...

**Comment by woothu** [comment]
I see in vue-select versions 2.x this event is not available, it is introduced from 3.x versions, instead you have onChange and onInput props:
https://vue-select.org/guide/upgrading.html#events-instead-of-callbacks

**Comment by jakubstankowski** [comment]
Great, it's work thanks !
