### ISSUE TITLE
Problem with code-editors from coreui - show code only after click 

### ISSUE THREAD

**Issue by jakubstankowski** [coreui/coreui-vue#30]
Hi everyone!

I have problem with code editor's from coreui.  It's working correctly, i mean - show code every time only after click in this editor's. I don't know why it's work that, thanks for helping. 

` import Vue from 'vue'
  import VueCodeMirror from 'vue-codemirror'
  // require styles
  import 'codemirror/lib/codemirror.css'
  import 'codemirror/theme/material.css'
  import 'codemirror/theme/eclipse.css'
  import 'codemirror/mode/markdown/markdown'
  import 'codemirror/mode/javascript/javascript'
  import 'codemirror/mode/xml/xml'

  import sampleCode from './_examples'
  Vue.use(VueCodeMirror);
  export default  {
    name: 'code-editor-test',
    components: {
      VueCodeMirror
    },
    data() {
      return {
        code: sampleCode.xml,
        editorOption: {
          tabSize: 4,
          styleActiveLine: true,
          lineNumbers: true,
          lineWrapping: true,
          line: true,
          mode: 'xml',
          theme: 'eclipse',
          autofocus: true
        },
        selectedMode: 'xml',
        selectedTheme: 'eclipse'
      }
    },
    computed: {
      codemirror () {
        return this.$refs.vueCm.codemirror
      }
    },
    methods: {
      onThemeChange (e) {
        this.editorOption.theme = e.target.value
      },
      onModeChange (e) {
        this.editorOption.mode = e.target.value
        this.code = sampleCode[this.editorOption.mode]
      }
    },
    mounted() {
      if (this.codemirror.options.autofocus) {
        this.codemirror.setSize('100%', '50vh')
        this.codemirror.focus()
      }
      setTimeout(() => {
        this.code += '\n\n\t~haha~'
      }, 2000)
    },
    props: [],

}`

![Zrzut ekranu (57)](https://user-images.githubusercontent.com/36790120/58417253-806a4f80-8084-11e9-814b-58ec08fc0152.png)

**Comment by woothu** [comment]
This is probably CodeMirror related issue.
https://stackoverflow.com/questions/8349571/codemirror-editor-is-not-loading-content-until-clicked
