### ISSUE TITLE
Second level sidebar dropdown auto-opens

### ISSUE THREAD

**Issue by willsned** [coreui/coreui-vue#31]
I'm using the sidebar components with nested dropdowns. I want all my dropdowns to be closed on load, which is the case for the first level of dropdown, but the second level dropdowns are always opened on load. I've traced the issue to the second level of dropdown being loaded with the open class applied by default. I've tried to remove the open class as soon as the element loads, but that creates an accordion effect of opening and closing the dropdown I don't want. Is there a way I could load the dropdown without the open class? Thanks

**Comment by xidedix** [comment]
hi @willsned 
We've tried to reproduce your issue with no luck.
Please make sure you've got proper routes config in `src/router/index.js` and paths in `src/_nav.js`

**Comment by willsned** [comment]
Thanks for the suggestion, but it turns out my error was with the sidebarNav.vue. I forgot I unnecessarily changed the file to make a SidebarNavDropdown without passing a url (specifically I removed the line :url="childL1.url" from the second level dropdown), which causes the dropdown to auto-open
