### ISSUE TITLE
Switch fires @change event already on initialization

### ISSUE THREAD

**Issue by felix-voicehub** [coreui/coreui-vue#32]
The Switch (https://github.com/coreui/coreui-vue/blob/master/src/components/Switch/Switch.vue) already fires it's @change event when the page loads and it gets its initial value.

This is unexpected. It should only fire when the initial value changes.

**Comment by woothu** [comment]
Now component assumes that every check is a change. I agree with you it shouldn't work this way, but for now, such change could cause possible breaking change. 

This component will be totally reworked in version 3 which is currently in alpha state. To check upcoming changes you can check new CSwitch component docs: https://coreui.io/vue/docs/3.0/components/Switch.html
