### ISSUE TITLE
Problem at SidebarNav in iOS safari

### ISSUE THREAD

**Issue by vata03** [coreui/coreui-vue#33]
I'm using SidebarNav. In PC, It's working fine perfectly.
But, In mobile safari at iOS, first tap don't cause navigate.

This problem same at Core UI for Vue sample site.
Angular and React sample site doesn't occur this issue.

Thanks for reply.

**Comment by xidedix** [comment]
Hi @vata03 - thanks for the heads-up!
Confirmed. Mobile Safari for iOS: (only) the first tap on SidebarNav doesn't work as expected.
We are going to investigate the issue.

**Comment by vata03** [comment]
Hi @xidedix.
Thanks ! I'm waiting for good news with hopefully.

**Comment by njwest** [comment]
Same issue, on mobile Chrome on iOS, have to double-tap to execute navigation

Any ideas re: why this is happening? (this issue is a bit stale)

**Comment by njwest** [comment]
Note: Only the first menu selection requires double-tap on iOS, if the menu doesn't re-render on the next page only one tap is required to navigate to another nav item

**Comment by njwest** [comment]
Hmm, I am concerned that this issue has not received any attention in some months as this is core/basic web app functionality, @xidex @mrholek do ya'll need some help with this?

**Comment by mrholek** [comment]
@njwest this issue will be resolved in CoreUI 3.1.0

**Comment by vata03** [comment]
> @njwest this issue will be resolved in CoreUI 3.1.0

Thank you for your reply. I look forward to the next version.

**Comment by woothu** [comment]
@vata03 could you please check if everything works fine in 3.2.0 version?

**Comment by woothu** [comment]
I mean style library `@coreui/coreui` not the component library

**Comment by vata03** [comment]
> I mean style library `@coreui/coreui` not the component library

I see. And, That's works fine perfectory when update style library.
Was it originally a style library issue?

Anyway, My problem is solved. Thank you for your correspondence.

**Comment by woothu** [comment]
@vata03 Yes, I suppose that it occured because iOS treat first tap as hover.
