### ISSUE TITLE
ChartJS Tooltips wrong positioning with multiple charts

### ISSUE THREAD

**Issue by felix-voicehub** [coreui/coreui-vue#34]
When I have multiple charts on the same page, the tooltip positioning gets a little funky.
The first chart works perfectly fine, but when hovering another chart, the tooltips show up on the first chart you hovered on that page:

![chart_bug](https://user-images.githubusercontent.com/49151885/61942185-307f0a80-af99-11e9-8d40-45e681bfdd4b.gif)

**Comment by woothu** [comment]
Can you share the code?
I assume that you are using line-example component, and you didn't assign unique chartId prop like in:
 https://github.com/coreui/coreui-free-vue-admin-template/blob/master/src/views/Charts.vue

**Comment by felix-voicehub** [comment]
Yes, you are correct. This seems to fix it.
