### ISSUE TITLE
Update SidebarNav item locale

### ISSUE THREAD

**Issue by sebastian-raubach** [coreui/coreui-vue#36]
The `SidebarNav` doesn't appear to be responsive when it comes to the `name` property. I've got a Vue.js app using vue-i18n for internationalization:
```
{
  name: this.$t('menuHome'),
  url: '/home',
  icon: 'mdi mdi-18px mdi-home'
}
```
It shows the correct text initially, but if I switch between locales, the menu doesn't update. I tried specifying the `name` as a function so that it can be called again after the locale changed, but it won't accept a function.

**Comment by sebastian-raubach** [comment]
My current workaround is to completely recreate the `nav` array that is passed into `navItems` when the locale changes, which works but isn't ideal.

**Comment by woothu** [comment]
This is how Vue reactivity system works,  optionally you can create a computed property in DefaultContainer.vue, in which you will just return all _nav.js code, then it should be reactive and performant.
