### ISSUE TITLE
Bootstrap typehead autosuggest list  is hover, after swipe the list

### ISSUE THREAD

**Issue by jakubstankowski** [coreui/coreui-vue#37]
I have problem with suggest list, which is hidden, after when i want swipe suggest list, it's only available in tabs likein code
`<b-tabs>
                    <b-tab title="Autosuggest">
                        <vue-bootstrap-typeahead
                                v-model="query"
                                :data="['Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada','Canada', 'USA', 'Mexico']"
                        />
                    </b-tab>
                </b-tabs>`

![Zrzut ekranu (89)](https://user-images.githubusercontent.com/36790120/65026502-f7c83580-d938-11e9-95db-eb6246010735.png)
![Zrzut ekranu (90)](https://user-images.githubusercontent.com/36790120/65026510-fac32600-d938-11e9-9327-670b1b7de2d6.png)

i use this package:
- https://alexurquhart.github.io/vue-bootstrap-typeahead/#/

thanks for answer!

**Comment by woothu** [comment]
Hi, b-tabs and b-tab are components from bootstrap-vue library, we just implement them in our template.
