### ISSUE TITLE
error occured on nuxt framework

### ISSUE THREAD

**Issue by corgidisco** [coreui/coreui-vue#4]
I use coreui/vue in the nuxt framework, and I get the following error:

```
 ERROR  Nuxt error

  ReferenceError: window is not defined

  - index.js:1
    [frontend]/[vue-perfect-scrollbar]/dist/index.js:1:28881

   . . . .
```

Maybe the following file is the problem.

- https://github.com/coreui/coreui-vue/blob/master/src/components/Sidebar/SidebarNav.vue

**Comment by sergiomedinavalentin** [comment]
+1

**Comment by apauriche** [comment]
It's because the vue-perfect-scrollbar dependency used in coreui-vue does not support yet the SSR.

However, you can use your nuxt project with coreui in SPA only mode. (npm run dev --spa)
