### ISSUE TITLE
CSidebarBrand wrappedInLink should open with target="_blank"

### ISSUE THREAD

**Issue by fancydev18** [coreui/coreui-vue#40]
Hi,

We'd like to link to main site from the admin sidebar brand logo.
However, clicking on it navigates away from the admin, since there's no target="_blank"

Would you please make it open in a new window, or make wrappedInLink an object, so we can pass href and target attributes?

https://github.com/coreui/coreui-vue/blob/v3-alpha/src/components/sidebar/CSidebarBrand.vue

Thanks!

**Comment by woothu** [comment]
Hi!
It is an object, you can pass all of CLink props.
