### ISSUE TITLE
CSidebarNavLink: please let us specify a custom class

### ISSUE THREAD

**Issue by fancydev18** [coreui/coreui-vue#42]
Would it be possible to please let us specify a custom class for some sidebar links, in 3.0?

```
            'CSidebarNavLink',
            {
                props: {
                    name: '...',
                    to: '...',
                    icon: 'fas fa-calendar-alt',
                    class: 'admin-only'
                }
            }

```

The class should be added to generated `li`:
```
<li class="c-sidebar-nav-item admin-only">
```

Thanks!

**Comment by woothu** [comment]
Hi! 

This prop already exists, it is called 'addLinkClasses' https://github.com/coreui/coreui-vue/blob/3.0.0-alpha.7/src/components/sidebar/CSidebarNavLink.vue

**Comment by fancydev18** [comment]
Thanks!

**Comment by woothu** [comment]
In the latest release component name changes to CSidebarNavItem. I encourage you to test the beta version of the library (docs: https://coreui.io/vue/docs/). It would be helpful if you give us some feedback :)

**Comment by fancydev18** [comment]
Sure @woothu ! Thanks for the update :)

I'm using only the sidebar components, importing them like this in main.js
```
import CSidebar from '@coreui/vue/src/components/sidebar/CSidebar'
Vue.component('CSidebar', CSidebar)
import CSidebarBrand from '@coreui/vue/src/components/sidebar/CSidebarBrand'
Vue.component('CSidebarBrand', CSidebarBrand)
import CRenderFunction from '@coreui/vue/src/components/render-function/CRenderFunction'
Vue.component('CRenderFunction', CRenderFunction)
import CSidebarNav from '@coreui/vue/src/components/sidebar/CSidebarNav'
Vue.component('CSidebarNav', CSidebarNav)
import CSidebarNavItem from '@coreui/vue/src/components/sidebar/CSidebarNavItem'
Vue.component('CSidebarNavItem', CSidebarNavItem)
import CSidebarNavDivider from '@coreui/vue/src/components/sidebar/CSidebarNavDivider'
Vue.component('CSidebarNavDivider', CSidebarNavDivider)
import CSidebarMinimizer from '@coreui/vue/src/components/sidebar/CSidebarMinimizer'
Vue.component('CSidebarMinimizer', CSidebarMinimizer)
import CToggler from '@coreui/vue/src/components/toggler/CToggler'
Vue.component('CToggler', CToggler)
import CEmitRootEvent from '@coreui/vue/src/directives/CEmitRootEvent'
Vue.directive('c-emit-root-event', CEmitRootEvent)
```

After updating, I'm getting this error:
```
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <CRenderFunction> at node_modules/@coreui/vue/src/components/render-function/CRenderFunction.vue
         <CSidebar> at node_modules/@coreui/vue/src/components/sidebar/CSidebar.vue
           <TheSidebar> at src/containers/TheSidebar.vue
             <TheContainer> at src/containers/TheContainer.vue
               <App> at src/App.vue
                 <Root>
```

Note that CRenderFunction is imported in main.js (removing it gives another error).
What am I doing wrong?

Feedback: I find confusing using `_name` and `name` in 
https://github.com/coreui/coreui-free-vue-admin-template/blob/v3-alpha/src/containers/_nav.js

`_name` could be `component`
`name` could be `title`

Looking forward to get rid of the error and being able to test the functionality too.

**Comment by woothu** [comment]
Could you share the code that you are passing to CRenderFunction. 

(Check out docs for '_name' confusion, we didn't name it '_component' because it can be also HTML node like div)

**Comment by fancydev18** [comment]
```<CRenderFunction :contentToRender="nav" />```

I see now this changed in latest version to
```<CRenderFunction flat :contentToRender="nav" />```

Adding `flat` fixes the error. Is that required?

After changing `icon` to `fontIcon`, all seems to work! And CIcon/coreui-icons is no longer required :tada:

**Comment by woothu** [comment]
It is required if you use flat API ;)

P.S. If you don't need to generate menu automatically it might be more readable not to use CRenderFunction at all.

**Comment by fancydev18** [comment]
> P.S. If you don't need to generate menu automatically it might be more readable not to use CRenderFunction at all.

How would that work? I only know about the example in
https://github.com/coreui/coreui-free-vue-admin-template/blob/v3-alpha/src/containers/_nav.js

Thanks!

**Comment by woothu** [comment]
Just use normal vue component tree, CRenderFunction is just rendering components, nothing more.
