### ISSUE TITLE
Add event to SidebarToggler

### ISSUE THREAD

**Issue by rfink** [coreui/coreui-vue#43]
When using many popular charting or table libraries with CoreUI, the SidebarToggler (and SidebarMinimizer) can mess with the widths of the components, due to their nature. The SVGs frequently need re-rendered. Devextreme is an example of this. With the SidebarMinimizer, this is easy to force a redraw by listening to the cui-sidebar-minimize event being emitted. A similar event is not emitted in the SidebarToggler, and it appears we cannot capture the click event due to the stopPropagation method. Would it be possible to emit a similar event on this component?

Or, if I'm doing something unintelligent, please let me know. Thank you!

**Comment by woothu** [comment]
Hi! 

The sidebar mechanism has been completely redesigned in version 3. Check out the 3.0.0-beta.0 version where such problem wouldn't occur

**Comment by rfink** [comment]
Hello and thank you for your response. When you refer to completely redesigned, do you mean that the event will now be emitted? Or that it won't cause element resizes? Any details I could check into?

**Comment by woothu** [comment]
It doesn't stop propagation, so the @click.native is possibility, moreover, there is directive c-v-emit-root-event (https://coreui.io/vue/docs/directives/emit-root-event.html) , which allows for emitting events on $root node which could be listened all over the app.
