### ISSUE TITLE
How to active dark theme on v3?

### ISSUE THREAD

**Issue by daynt** [coreui/coreui-vue#44]
I'm trying to change my project to CoreUI v3 PRO Vue beta v1.

I tried to uncomment the dark theme scss line in style.scss but the theme file doesn't exist anymore in CoreUI v3.
```
// Import styles with dark layout
// If you want to use dark layout uncomment next line
@import "~@coreui/coreui-pro/scss/themes/dark/coreui-dark";
```

Are there any solution to enable the dark theme or I have to wait for the next beta versions?

**Comment by woothu** [comment]
Hi, this comment is misleading, you can turn dark theme by adding 'c-dark-theme' class to <body>

**Comment by daynt** [comment]
Works! Thank you.

**Comment by crabvn** [comment]
works, please update the docs/code

Anyway, thanks alot

**Comment by knutole** [comment]
@daynt This doesn't work for me. In fact, there is no mention of `c-dark-theme` anywhere else in the codebase. Has this been updated yet again? Basically I'm unable to enable Dark mode for Vue Admin Template.
