### ISSUE TITLE
CoreUi v3, CDataTable table-filter and other slot

### ISSUE THREAD

**Issue by rusicsemenov** [coreui/coreui-vue#47]
Hello, how i can change table-filter slot, i want translate "Filter:" and alse "Item per page:"?

I undertent, i can create new input and use "tableFilterValue" but maybe you did some for us.

**Comment by woothu** [comment]
Hi! Thank you for your input, adding functionality to change these hardcoded descriptions is a very good idea, we will probably introduce it in the next version.

For now, you can use slots as I described in #49

**Comment by rusicsemenov** [comment]
I tried use slot, but if i don't initiated tableFilter, filter doesn't work. I think need add watcher in `CDataTable.vue` for `tableFilterValue` and called `tableFilterChange`, it works without init filter

**Comment by woothu** [comment]
@rusicsemenov It should be fixed with latest release I just published. It is not yet available on NPM.
To install it please specify github release in package.json:

```json
    "@coreui/vue": "coreui/coreui-vue#3.0.0-beta.6",
```

Let me know if you still have any problems :)

**Comment by rusicsemenov** [comment]
We bought pro version, we can update core?

**Comment by woothu** [comment]
Oh, I have missed it. Try now:

```json
"@coreui/vue": "coreui/coreui-vue#0b341bf566851c7906b0cb19eb04d105b1708000"
```

**Comment by rusicsemenov** [comment]
Yes, worked! I think need add change `this.perPageItems = val` to `this.perPageItems = parseInt(val)` because we can send streeng ) and this do error in concole.

**Comment by woothu** [comment]
You cannot send string because type of itemsPerPage is defined as Number.

**Comment by rusicsemenov** [comment]
Realy ?)) [screen](https://drive.google.com/open?id=1UWvlJMe0IAo_RD1Y_0HqbzLonP4YexFV)

**Comment by woothu** [comment]
That's exactly how Vue type checking displays errors. It says that you have to pass Number.

**Comment by rusicsemenov** [comment]
Yes, I know, thank you. Have a nice new year and holidays.
