### ISSUE TITLE
v-model not work for CInputs and CInputRadio 

### ISSUE THREAD

**Issue by HAL0594** [coreui/coreui-vue#48]
I am trying to obtain the value with v-model with a CInputs and CInputRadio but it does not take changes the initial value, and proven with the only component that works for me it is with CInput

**Comment by woothu** [comment]
In HTML value does not change on checkbox click, the thing that changes is checked value. You can track checked value by checked prop with .sync modifier.

https://coreui.io/vue/docs/components/form-components.html

**Comment by slav0nic** [comment]
@woothu can you please comment my question or better create new issue?

**Comment by woothu** [comment]
This default Vue workflow is not available in `CCheckbox` component.
