### ISSUE TITLE
CoreUi v3 CSelect and v-model

### ISSUE THREAD

**Issue by rusicsemenov** [coreui/coreui-vue#51]
Hello, in source CSelect emit `update:value`, but in manuals you write events: input, what you will be use? We must use v-model or listen update:value?

**Comment by woothu** [comment]
Hi, actually this event description in docs id obsolete. thank you for report.

Btw. In vue events named "updated:{propName}" could be tracked by :propName.sync="currentValue", in this example value.sync

**Comment by rusicsemenov** [comment]
Yes thanks, i read "evetns -> input" and write v-model.
