### ISSUE TITLE
CoreUi v3 Modal and scoped method 'hide()'

### ISSUE THREAD

**Issue by rusicsemenov** [coreui/coreui-vue#52]
Hello you wrote  `In all slots there is available scoped method 'hide()' `
- First in [manual ](https://coreui.io/vue/docs/components/modal.html#cmedia-api)
you wrote CMedia API i thnk need CModal.
- Also `In all slots there is available scoped method 'hide()' .....` but you don not bind `:hide`, and i have warn `Property or method "hide" is not defined`

```
                <template #footer>
                    <div>
                        <CButton
                            color="info"
                            @click="hide"
                            >{{ $t("close") }}</CButton
                        >
                    </div>
                </template>
```

What am I doing wrong?

**Comment by woothu** [comment]
Hi, thank you for this report.

hide() method was removed, to simplify component - now the only way to control visibility by API is by "show". We will update these docs.
