### ISSUE TITLE
Override the CSidebarNavLink template

### ISSUE THREAD

**Issue by STDGA** [coreui/coreui-vue#55]
Hi,
is there anyway to use custom Template in sidebar items?
i didnt find any named slot in there:
https://github.com/coreui/coreui-vue/blob/3.0.0-alpha.7/src/components/sidebar/CSidebarNavLink.vue

Thank you

**Comment by woothu** [comment]
There is no named slot, default slot overrides content inside of the link. 

Notice that version that you use is 3.0.0-alpha.7 and API of this component is already different than in docs. I highly recommend you switching to the beta version (stable version will be available probably next week).

**Comment by STDGA** [comment]
Thank you, 
will you provide any method to override the default template for Navlink in the beta version?

**Comment by woothu** [comment]
You just pass whatever you want in default slot.
