### ISSUE TITLE
Pagination Table

### ISSUE THREAD

**Issue by peter81git** [coreui/coreui-vue#56]
I'm trying to pass an object to pagination when using cdatatable. However the page number does not change. The objects tried: {pages:'51'} , {pages:51} or even {props:{pages:51}}
Is this an issue or I'm missing something in the object
Also the documentation could have an example for this prop.

**Comment by woothu** [comment]
Hi! It is not possible to pass pages number, CDataTable is calculating pages number based on:
- How many items you have passed,
- itemsPerPage prop,

If you want to define non-existing pages (i.e. with not loaded items) you have to make your own CPagination component.

**Comment by peter81git** [comment]
> Hi! It is not possible to pass pages number, CDataTable is calculating pages number based on:
> 
> * How many items you have passed,
> * itemsPerPage prop,
> 
> If you want to define non-existing pages (i.e. with not loaded items) you have to make your own CPagination component.

Tank you for the quick reply.
If is not possible to pass pages number could you please update the docs where it says:

`pagination | false | Boolean/Object

Enables default pagination. Set to true for default setup or pass object with additional CPagination props.`

Thank you.

**Comment by woothu** [comment]
Yes, we will make a better 'pagination' prop description. Thank you for the report! :)
