### ISSUE TITLE
Add ability to get current filtered items in CDataTable 

### ISSUE THREAD

**Issue by CVeniamin** [coreui/coreui-vue#58]
After looking at the docs CDataTable does not have an event that indicates what are the current filtered items after one applies a filter to a specific column or searched in a table.

Hence, after looking at the code I saw that this can be easily achieved by emitting an event after  https://github.com/coreui/coreui-vue/blob/2ced24b5588e00d7e8c9ecdd42436f21868b4de1/src/components/table/CDataTable.vue#L455 and https://github.com/coreui/coreui-vue/blob/2ced24b5588e00d7e8c9ecdd42436f21868b4de1/src/components/table/CDataTable.vue#L463 for instance 
```js
this.$emit('update:table-items', this.currentItems)
```
The name of the new event is mere indicative.

**Comment by woothu** [comment]
Hi! Thank you for this idea!
What are the cases for using such an event?

Btw. 'currentItems' are not filtered items, but visible items. You probably meant 'tableFiltered' or 'sortedItems' (filtered items after applied sorting).

**Comment by CVeniamin** [comment]
You are right! Was about to edit the issue since I saw that `currentItems` are the items visible items as you mentioned...

One of the use cases would be to allow "download" the filtered items to a xlsx/csv file.

**Comment by woothu** [comment]
Very useful use-case! We will add this feature :)

**Comment by CVeniamin** [comment]
Awesome!

**Comment by woothu** [comment]
Feature introduced in 3.0.0-beta.11, commit: ea92ae74bacdf2ca2d09f3cdf09bb8933ab79d48
