### ISSUE TITLE
[CDataTable] Add cell (double-)click event

### ISSUE THREAD

**Issue by darthf1** [coreui/coreui-vue#59]
```yaml
    "@coreui/coreui": "3.0.0",
    "@coreui/icons": "1.0.1",
    "@coreui/vue": "3.0.0",
```
Currently the `CDataTable` has a `row-clicked` event. I would like to request an additional event when a cell is (double-?) clicked, which should return the cell and value of the clicked cell. We have business logic where the user is redirected to a route based on which cell (header/value) the user has clicked on. With the current available events I don't know which cell/value is clicked.

Could be like this:
http://tabulator.info/docs/4.5/callbacks#cell

**Comment by woothu** [comment]
Because there is no way to add an event on a slot (cells can be represented as slots), modification has been done on the 'row-clicked' event so the third argument with column name string is now available.
