### ISSUE TITLE
[CDataTable] Select multiple rows

### ISSUE THREAD

**Issue by darthf1** [coreui/coreui-vue#61]
```yaml
    "@coreui/coreui": "3.0.0",
    "@coreui/icons": "1.0.1",
    "@coreui/vue": "3.0.0",
```

It is already possible to select one row by clicking on it. I would like to have the possibility to select multiple rows.

Maybe by:
- Shift + click adds a row
- A prop which enables multi-click, and each subsequent click selects an additional row

**Comment by woothu** [comment]
We decided that such functionality will not be included in CDataTable for now, but an example of achieving this functionality with CDataTable will be published on our pro template, after adding active row styling to our CSS library.
