### ISSUE TITLE
[CDataTable] Allow nested objects / fields

### ISSUE THREAD

**Issue by darthf1** [coreui/coreui-vue#62]
I would like to request support for nested objects / fields.

```js
item: {
  id: 1,
  code: 'xx',
  unit: {
    description: 'myDescription'
  }
}

fields = [
  'id',
  'code',
  'unit.description'
]
```
```html
<c-data-table :items="items" :fields="fields" />
```

This would result in a table with a `description` column with the value derived from the `unit` object. 
Currently if I do this the field value is `undefined`.

**Comment by woothu** [comment]
Scoped slots are made for unusual cases like this just 

```js
fields = [
  'id',
  'code',
  'unit'
]
```

```html
<c-data-table :items="items" :fields="fields">
      <template #status="{item}">
        <td>
            {{item.unit.description}}
        </td>
      </template>
</c-data-table>

```

**Comment by darthf1** [comment]
Fair enough. The reason I came up with this is because we previously used a different component which supported this feature. I totally forgot about using this through slots, which is the better option I guess. Didn't know this case was unusual though =)

Thanks!

**Comment by woothu** [comment]
Actually, it is recommended to do this in another way: computing your items before passing to the table, since filtering and sorting would not work correctly otherwise.

This feature has its use cases, but component shouldn't cover every use-case since it would grow to the infinity. (performance, maintainability and the component complexity for users are issues here)

**Comment by darthf1** [comment]
In my case both (column-)filtering and sorting are done externally. The API I'm using supports filtering and sorting on nested elements.

https://api-platform.com/docs/core/filters/#filtering-on-nested-properties

**Comment by woothu** [comment]
Yes, this is a valid use case, I get your point. ;) 

Btw. You can keep your nested data, and just add an additional key to the item, just don't mention nested data key in 'fields' prop. This way you preserve your desired structure and simplify CDataTable usage.
Then computing could look like this
```
computed: {
  computedItems () {
    return rawItems.map(item => {...item, { unit: item.unit.description }})
  }
}
```

**Comment by InfiniteCoder96** [comment]
How to Allow nested objects / fields in react?

**Comment by MMahendra001ScaleTech** [comment]
I have data with nested objects and arrays, I use CDataTable to represent them at the front end, now I want the functionality where users can search within that table to look for specific things like match id or user name. So I use columnFilter
tableFilter to search for specific things in them, but it seems that it will look for things that are in their immediate keys, only those searches will work but if you are looking for something and it is nested deep down in some objects or arrays then it won't work.

**Comment by MMahendra001ScaleTech** [comment]
> How to Allow nested objects / fields in react?

              items={disputeListData}
              fields={[
                { key: 'created', label:"Creation Date", _classes: 'font-weight-bold' },
                { key: 'gameUserName', label:"Game User Name" },
                { key: 'gamePartnerName', label:"Game Partner Name" },
                'competition',
                'user',
                'userId',
                'uuid', 
              ]}
              columnFilter
              tableFilter
              hover
              striped
              itemsPerPage={5}
              activePage={page}
              scopedSlots={{
                user:(items) => {return (<>
                  <td>
                    <CBadge>{items.user?.username || 'undefined'}</CBadge>
                  </td>
                  <td>
                    <CBadge>{items.user?.id|| 'undefined'}</CBadge>
                  </td>
                  </>                  
                )},
                competition:(items) => (
                  <td>
                    <CBadge>{items.competition.id} </CBadge>
                  </td>
                ),
                uuid:(items) => (
                  <td>
                    <Link to={`/dispute/${items.uuid}`}>View Details</Link>
                  </td>
                ),
                            
              }}

**Comment by DuddyRosenberg** [comment]
How would i do scopedSlots in Vue? I need a second row for each row

**Comment by DuddyRosenberg** [comment]
Anyway u can get a another full row after each row.
https://coreui.io/react/docs/3.3/components/CDataTable/
Here they have a collapse but i can’t figure out how to this in Vue
