### ISSUE TITLE
CTabs event not working 

### ISSUE THREAD

**Issue by koneriranjith** [coreui/coreui-vue#63]
`<CTabs @update:activeTab="activeTab"></CTabs>`

As per the https://coreui.io/vue/docs/introduction/ => V 3.0.0 
has @update:activeTab event but this event is not working. I checked the GitHub code some of the versions not returning the event emit.

![image](https://user-images.githubusercontent.com/10670647/75438660-5e3c8f80-597e-11ea-8bb4-fe45a9997146.png)

**Comment by woothu** [comment]
Yes, this feature is available only since 3.0.0-beta.11. If you have the current version it is possible that you duplicate 'activeTab' varaible

**Comment by yaswanthkoneriomni** [comment]
`<CTab @click="someFunction"/> `this is also not working @woothu

**Comment by woothu** [comment]
@yaswanthkoneriomni I responded for your issue https://github.com/coreui/coreui-free-vue-admin-template/issues/199
