### ISSUE TITLE
Using CoreUI and BootstrapVue

### ISSUE THREAD

**Issue by AnReZa** [coreui/coreui-vue#65]
In my project, I want to use CoreUI and BootstrapVue. Therefore, I modified my App.vue file as follows:

```html
<template>
  <router-view></router-view>
</template>

<script>
export default {
  name: 'App'
}
</script>

<style lang="scss">
    //Import bootstrap
    @import '~bootstrap';
    @import '~bootstrap-vue';
    //Import Main styles for this application
    @import 'assets/scss/style';
</style>
```

But as soon as I import bootstrap and bootstrap-vue, it ruins the layout of some components, mainly the horizontal nav bar. Is there a "correct" way to use both libs in coexistance?

**Comment by woothu** [comment]
If you want to use CoreUI styles then do not import bootstrap, just CoreUI styles (they cover bootstrap classes, but have minor differences that could break styles)

**Comment by AnReZa** [comment]
@woothu With the CoreUI classes alone, stuff like model dialogs don't seem to work at all. Is that correct?

**Comment by woothu** [comment]
Did you mean modal dialogs? They are working fine, you can check this on coreui-free-vue-admin-template.

**Comment by AnReZa** [comment]
@woothu I mean bootstrap-vue methods like `this.$bvModal.msgBoxOk` and `this.$bvToast.toast`.

**Comment by woothu** [comment]
I doubt that bootstrap-vue component javascript methods can be broken by changes in the external css library.

**Comment by AnReZa** [comment]
@woothu For some strange reason, it works now. However, do I need to import the additional bootstrap-vue css file?

**Comment by woothu** [comment]
It depends on which bootstrap-vue components do you use. Some of their components don't require additional css. You can check out their css to grasp it.

**Comment by AnReZa** [comment]
@woothu I can't really tell right now, The application we're talking about is under active development right now.

**Comment by woothu** [comment]
So you better stay with bootstrap-vue styles import

**Comment by AnReZa** [comment]
@woothu So I guess, this would be the right order:

```html
<style lang="scss">
    //Import Main styles for this application
    @import 'assets/scss/style';
    //Import bootstrap
    @import '~bootstrap-vue';
</style>
```

If I put bootstrap-vue before the main style, as it's said in the main documentation, I get an error. It looks like it can't access some scss dependencies then.

**Comment by woothu** [comment]
Yes, this is the right order. 

Anyway, we encourage you to give CoreUI Vue components a try.

Have no bugs and smooth development! :)

**Comment by AnReZa** [comment]
@woothu Thank you! bootstrap-vue delivers some nice wrapper templates, so you can, for example, create a table from an object with a single-liner instead of building the whole template up from scratch.

```
<b-table striped hover :items="pickingList" :busy="serviceIsBusy" show-empty>
    <template v-slot:empty="scope">
        <h4>{{ scope.emptyText }}</h4>
    </template>
    <template v-slot:emptyfiltered="scope">
        <h4>{{ scope.emptyFilteredText }}</h4>
    </template>
</b-table>
```

Makes development much faster and easier in some cases.

**Comment by woothu** [comment]
We deliver similar functionality:
https://coreui.io/vue/docs/components/table.html
More examples:
https://coreui.io/vue/demo/3.0.0/#/tables/advanced-tables

If you prefer one liners over building templates, you can also compare our input API vs bootstrap-vue API
