### ISSUE TITLE
[Question] How to localize

### ISSUE THREAD

**Issue by NikoGrano** [coreui/coreui-vue#67]
How can I localize https://github.com/coreui/coreui-vue/blob/master/src/components/table/CDataTable.vue#L147?

This is just one example. 

If this is something what havent been discussed or think about, I could create there new prop, called `localization`. That would be object with example data of

```typescript
localization: {
    error-no-results: string = 'No filtering results',
    error-no-items: string = 'No items',
    
}
```

This is just pure thinking on the spot, but hardcoding these in english into the component, is not really the way to do it.

**Comment by woothu** [comment]
You are correct, the solution for this is using 'no-items-view' slot. 

Anyway, we will consider adding additional prop.

**Comment by woothu** [comment]
noItemsView prop was added in f1304966a2fb95aa0e0b7d75e85fc6beb35f1594, and will be available with the next release
