### ISSUE TITLE
[Vue warn]: Do not use built-in or reserved HTML elements as component id: Switch

### ISSUE THREAD

**Issue by d-pollard** [coreui/coreui-vue#7]
### The Issue

I get the following warning whilst running the library in my new project, trying to register the components globally (as shown in the `readme`:

> **[Vue warn]: Do not use built-in or reserved HTML elements as component id: Switch**

`<switch>` element documentation page: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/switch

#### [From the Vue documentation style guide:](https://vuejs.org/v2/style-guide/#Base-component-names-strongly-recommended)
> **Component names should always be multi-word, except for root App components.** This prevents conflicts with existing and future HTML elements, since all HTML elements are a single word.

### Suggested Change
In order to stay compliant with the style guide, and prevent this from happening in the future, I propose we add a prefix to each of custom elements, and even maybe make the prefix customizable so that, if need be (for backwards compatibility) the prefix can be turned off:

**_Ex: `ui-switch`_**

**Comment by mohd-isa** [comment]
Getting the same warning

I think prefixing all elements is a great solution.

**Comment by AaronKaa** [comment]
How would I get past this error when using the LibraryModule ?

**Comment by woothu** [comment]
For now, you can remove import of switch component to LibraryModule in coreui-vue/src/index.js and then rebuild package (you need github config files to do this) or remove switch component from LibraryModule in build file.

This component name will be changed in the next version.

**Comment by AaronKaa** [comment]
Would you be able to give me a couple of pointers to do this - I've made the changes to the module and tried rebuilding but i still get the old version at the front end

**Comment by woothu** [comment]
You can check if the build is done right by checking dist files (there should be no Switch component in LibraryModule).

**Comment by cherryred5959** [comment]
@woothu  This issue has not been solved yet, is there any reason to close this issue?

**Comment by woothu** [comment]
I gave the instruction on how to solve this issue, for now, we cannot just introduce fix because it is a breaking change and we will introduce it in version 3.

**Comment by cherryred5959** [comment]
Thx, I'm looking forward to a quick release.
