### ISSUE TITLE
[CDataTable] thead-top slot

### ISSUE THREAD

**Issue by darthf1** [coreui/coreui-vue#70]
```
"@coreui/coreui": "3.0.0",
"@coreui/icons": "1.0.1",
"@coreui/vue": "3.0.0",
```
I would like request an additional `thead-top` slot for the CDataTable component, similar to the one in [Bootstrap](https://bootstrap-vue.js.org/docs/components/table/#comp-ref-b-table-slots)

In my case; in a `div` above the table I display a list of fields. Via a draggable interface, I want to 'drag' those fields to the correct column of the table. With the additional `thead-top` slot I have a top field available in each row with a draggle area, to which the field should be dragged.

I could also do this with a `<table>` in the `over-table` slot, but then the width of the columns wont match.

**Comment by woothu** [comment]
Feature introduced in f1304966a2fb95aa0e0b7d75e85fc6beb35f1594. It will be available in the next version.
