### ISSUE TITLE
<CDropdown doesnt get closed After clicking on <CDropdownItem>

### ISSUE THREAD

**Issue by yaswanthkoneriomni** [coreui/coreui-vue#71]
Before opening an issue:

- [Search for duplicate or closed issues](https://github.com/coreui/coreui-vue/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](./CONTRIBUTING.md)

When asking general "how to" questions:

- Please do not open an issue here

When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, etc...)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

When suggesting a feature, include:

- As much detail as possible for what we should add and why it's important to CoreUI Admin Template
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by woothu** [comment]
Hi! Thank you for the bud report!
CDropdown was closing only on $route change, now it is closed on every 'dropdown-item-click' event emitted on the CDropdown component.

**Comment by yaswanthkoneriomni** [comment]
> Hi! Thank you for the bug report!
> CDropdown was closing only on $route change, now it is closed on every 'dropdown-close' event emitted on it. (CDropdownItem is now emitting such event on CDropdown)

Can you give an example snippet to achieve this?

**Comment by woothu** [comment]
It is default behavior since 3.0.2 version

**Comment by yaswanthkoneriomni** [comment]
After the update 
` <CDropdownItem 
                      :key="index" 
                      v-for="({text,value, statusId}, index) in filters" 
                      @click="filterByStatus(statusId)">`

@click event is not getting fired

**Comment by woothu** [comment]
What do you mean by the default value of the dropdown?

Because click event is not emitted by CDropdownItem component (see docs for emitted events)

You can use @click.native instead

**Comment by woothu** [comment]
Actually I forgot that functional components have different events trigger, and didn't add them when I changed CDropdownItem from functional to a normal component. 

@click event is available again in the 3.0.3 version.
