### ISSUE TITLE
[CDataTable] Error in objectsAreIdentical with circular obj

### ISSUE THREAD

**Issue by ajm13** [coreui/coreui-vue#75]
`CDataTable` uses `JSON.stringify` in `objectsAreIdentical`. When `items` contains objects with circular references, `JSON.stringify` throws an error, and this will happen every time `items` or `sortedItems` changes.

This can be fixed by using a cache and providing a function to `JSON.stringify` to avoid circular references, like this example: 

```js
export const customStringify = function (v: any) {
  const cache = new Map();
  return JSON.stringify(v, function (key, value) {
    if (typeof value === 'object' && value !== null) {
      if (cache.get(value)) {
        // Circular reference found, discard key
        return;
      }
      // Store value in our collection
      cache.set(value, true);
    }
    return value;
  });
};
```
[from here](https://github.com/substack/tape/issues/434#issuecomment-382071275)

**Comment by woothu** [comment]
Hi! Thank you for this report! What is the use of passing circular objects to items?
