### ISSUE TITLE
[CSidebarNavItem] Icon props are not passed to CIcon 

### ISSUE THREAD

**Issue by CVeniamin** [coreui/coreui-vue#76]
I am trying to adjust the size of icon in the CSidebarNavItem by passing icon as an object, such as
```vue
<CSidebarNavItem 
  name="Dashboard" 
   to="/dashboard" 
   :icon="{name: 'cil-chart', size: '4xl'}"
/>
```
however the size prop is not passed to CIcon. 
However, creating a CIcon with the `size` prop works just fine 
```vue
<CIcon name="cil-chart" size="4xl"/>
```
After searching through the code I saw that CIconRaw is imported instead of CIcon
https://github.com/coreui/coreui-vue/blob/ad9f36c5bff5f9466bf1ebc8653228d1af659eef/src/components/template/CSidebarNavDropdown.vue#L19 

Could it be that importing CIconRaw instead of CIcon is to blame here?

**Comment by woothu** [comment]
Hi, thank you for the report! 

in fact, it doesn't work because 'customClasses' is set to 'c-sidebar-nav-icon' inside CSidebarNavItem overriding size prop in CIcon.

Hotfix:
```
<CSidebarNavItem 
  name="Dashboard" 
   to="/dashboard" 
   :icon="{name: 'cil-chart', customClasses: 'c-sidebar-nav-icon c-icon c-icon-4xl'}"
/>
```

We will think of a better solution, and fixing documentation.

**Comment by CVeniamin** [comment]
@woothu, thank you for the hotfix!
