### ISSUE TITLE
Striped table with details slot

### ISSUE THREAD

**Issue by slav0nic** [coreui/coreui-vue#77]
Striped table looks not correct if you enable details slot.

Here is what you will see if add `striped` to example table from docs https://coreui.io/vue/docs/components/table.html#usage

![striped](https://user-images.githubusercontent.com/199555/78331388-9b53fd00-758e-11ea-83af-600be2228e07.png)

**Comment by woothu** [comment]
It is because striped table coluors every 2nd row, and in this case every 2nd row is hidden. It is not bug because details row are not hidden by design, only on this specific example.
