### ISSUE TITLE
Simple "hello world" style example?

### ISSUE THREAD

**Issue by mrichman** [coreui/coreui-vue#78]
I'm just getting started with CoreUI and Vue.js. Is there a simpler "hello world" style example than the admin UI demo?

**Comment by woothu** [comment]
Documentation (coreui.io/vue/docs) delivers simple examples of specific components. Style examples are in CoreUI docs (coreui.io/docs).

**Comment by mrichman** [comment]
I was looking for a complete (but simple) working example, as opposed to the snippets provided in the docs.

**Comment by woothu** [comment]
https://codesandbox.io/embed/coreui-vue-select-t37uh?codemirror=1

**Comment by mrichman** [comment]
Thats exactly what I was after. Thank you!
