### ISSUE TITLE
styles?

### ISSUE THREAD

**Issue by Tim152** [coreui/coreui-vue#8]
Hello! Can you add styles for components?
I want use your library, but, unfortunately, for seeing coreui design I must looking for styles at coreui template and bootstrap sources :(

**Comment by xidedix** [comment]
hi @Tim152 
Thanks for raising the question. This is one of our milestones for v3.0 of CoreUI components. It's going to take some time since we have to rethink and rework the whole styles thing. 

Ideas and/or PR welcome!

**Comment by Tim152** [comment]
@xidedix sounds great! I would suggest to create styles library as dependence and encapsulate styles for coreui components only

**Comment by woothu** [comment]
Hi!
This feature is available in the latest alpha version:
https://github.com/coreui/coreui-vue/releases/tag/3.0.0-alpha.3
