### ISSUE TITLE
Simpler example than the admin panel?

### ISSUE THREAD

**Issue by mrichman** [coreui/coreui-vue#82]
There's an awful lot going on in the admin panel sample app. Is there a more basic example for Vue.js, perhaps one just showing sidebar/header/body/footer and little else? I'm having trouble starting from scratch, and beginning with the admin panel and then removing everything to get to a basic layout is troublesome. Thanks!

**Comment by woothu** [comment]
Hi! 

There are `coreui-pro-vue-admin-template-starter ` and `coreui-pro-vue-admin-template-starter-ts`  
admin templates with configuration, with a bare minimum to start. There are available in PRO version.

**Comment by mrichman** [comment]
So I have to pay for something that really should be included in the free version? This isn't a good way to foster adoption of your product.
