### ISSUE TITLE
CDataTable: fields key object

### ISSUE THREAD

**Issue by JonathanSchndr** [coreui/coreui-vue#84]
Hi!
Is it possible to pass an object to the key instead of a string?
I need a nested key.

Example:
```
fields: [
   { key: 'owner.role.name', label: 'Role' }
],
```

Docs: https://coreui.io/vue/docs/components/table.html#cdatatable-api
=> key (required)(String) - define column name equal to item key.

**Comment by woothu** [comment]
The topic has been discussed in #62
