### ISSUE TITLE
noFooter prop in CModal is not implemented

### ISSUE THREAD

**Issue by rocchidavide** [coreui/coreui-vue#85]
Hi, since I needed to hide modal footer, I see in documentation (https://coreui.io/vue/docs/3.0/components/Modal.html#cmedia-api) that should be available a `noFooter` prop, but it doesn't work. So I checked out CModal.vue component, and I didn't find any `noFooter` prop.

**Comment by woothu** [comment]
Hi! You are on the obsolete docs site, sorry!

current docs: https://coreui.io/vue/docs/

**Comment by woothu** [comment]
For your case, you can pass empty `footer-wrapper` slot

**Comment by rocchidavide** [comment]
Ops, sorry. So, how can I hide footer in modal? I tried to set template footer-wrapper without success like that:

` <template #footer-wrapper></template>`

**Comment by woothu** [comment]
pass something like an empty string, or empty <span>

**Comment by rocchidavide** [comment]
Ok, I tried and:
- `&nbsp;` doesn't work
- `<span>` is working

Thank you
