### ISSUE TITLE
Checkbox checked state instead of event.

### ISSUE THREAD

**Issue by buzzclue** [coreui/coreui-vue#86]
How can I get the checked state from checkbox instead of Event?

```Javascript
<CInputCheckbox :label="$t('front.test')" value="1" name="test" :size="size" v-model="test" ></CInputCheckbox>
```

test in this case always gets the Event I just want it to have true/false instead?

**Comment by woothu** [comment]
Instead of v-model use :checked.sync (both v-model and .sync are only shortcut syntax for binding value and receiving event, we use .sync version)
