### ISSUE TITLE
Dark mode disabled or readonly css

### ISSUE THREAD

**Issue by AlexZd** [coreui/coreui-vue#88]
It seems for `disabled/readonly` for `form-control` it is still using white colors.
<img width="307" alt="screenshot" src="https://user-images.githubusercontent.com/5249914/80919619-12da9f00-8d7c-11ea-8879-8a7b5f1bcdc1.png">

"User" field is readonly, "Platform" is normal

**Comment by woothu** [comment]
Both styles are present and work in the `coreui-pro` 3.1.1 version

![image](https://user-images.githubusercontent.com/32914662/80946547-8f0dca80-8dee-11ea-9a5e-fe0e4ab36f64.png)

**Comment by AlexZd** [comment]
Yes, sorry, didn't notice that there is override from my side.
