### ISSUE TITLE
What bootstrap-vue version is used?

### ISSUE THREAD

**Issue by hifall** [coreui/coreui-vue#89]
I bought CoreUI Pro V1 before, and it used bootstrap-vue V1.

I assume coreui/coreui-vue still use bootstrap-vue, but I can't find the version info either in the json files or your documentation.

I am asking this since bootstrap-vue fixed a lot of bugs since V1. I'd like to hang on to the latest.

Thanks!

**Comment by woothu** [comment]
Hi!

We are not using bootstrap-vue anymore. We introduced our own components library in version 3
https://coreui.io/vue/docs/introduction/
