### ISSUE TITLE
Filtering problem on data table

### ISSUE THREAD

**Issue by nnnayeem** [coreui/coreui-vue#90]
Hello everyone,

I am facing problem on filtering. Both column-filter and table-filter does not work if I use template inside datatable as slot on that specific coloumn.
```
<template #category="{item}">
    <td>
        <template v-if="item.category">{{item.category.category}}</template>
        <template v-else>
            <CBadge color="danger"> Category Not found</CBadge>
        </template>
    </td>
</template>                                       
```

My question is:

1. Is there any wrong the way I am doing things?
2. What I am missing?

**Comment by woothu** [comment]
Filter can detect string values, not objects.
The topic has been discussed in #62

**Comment by nnnayeem** [comment]
@woothu thank you for your reply. I have solved this by computing items before sending data to table.
But I am facing another problem. Based on data I have to use badge. So I was doing the following way:
```
<template #cartoon="{item}">
    <td>
        <span v-if="item.cartoons" v-for="(cartoon,n) in item.cartoons" class="font-weight-bold">type {{n+1}}:{{cartoon.size}} pcs<br></span>
        <CBadge v-else color="danger">Cartoon Not Found</CBadge>
    </td>
</template>
```
How do I get around this?

Note: I tried to include badge based on data while computing the items before sending to the table but the problem is data table does not render the badge rather shows plain html.

**Comment by woothu** [comment]
You were doing it correct, why would you change it?

**Comment by nnnayeem** [comment]
If I do this way my filter does not works.

**Comment by woothu** [comment]
Filters can work only on strings. This means that if you pass the object as cell content it couldn't be filtered.

slot modifications are without limits and have no connection to filtering.

**Comment by nnnayeem** [comment]
In the above example I am passing `cartoonn.size` which is not a object. I did not quite get it when you mention about passing object to cell content. Because `cartoon.size` is a string.

Can I render html passing as data to the item? Data is being escaped by the dataTable.

**Comment by woothu** [comment]
What is the item object structure? I mean that string has to be directly on the column key.

**Comment by nnnayeem** [comment]
Thank you @woothu I get it now. I was thinking table will filter the string that is generated inside td but it actually filters the data that is actually passed to the coloumn key.

**Comment by nnnayeem** [comment]
I did a little work around and it fixed my problem.
Before sending data to the table I simply assign data  to the coloumn key that the user would search. Then I did slot manipulation as per my requirement. As table filters data under the coloumn key, slot manipulation would not cause any problem. The following example would clear more:

Before sending data to the table I am doing this:
```
IndexAllProducts() {
    this.$store.dispatch('System/Request/MakeRequest', {type: 'get', url: '/api/products'}).then((res) => {
         if (!res.http_status && res.http_status !== 200 && !res.data) return this.items = []
              this.items = res.data.map((item) => {
                  return {...item, category: (_.has(item, 'category.category')) ? item.category.category : false, cartoon:this.formatCartoon(item.cartoons)}
         })
    }).catch((error) => {
         console.log(error)
    })
},

formatCartoon(cartoons) {
    // var cartoons = item.cartoons
    if (_.isEmpty(cartoons)) return `Cartoon Not found`

    var a = "";
    cartoons.forEach((item, index) => {
         a = a + `type ${index + 1}: ${item.size} pcs `
    })

    return a
},
```
In the format cartoon I am formatting the cartoon coloumn key as type 1: value 1 type 2: value 2. When users search they would search value 1, value 2 and table would filter the data under the coloumn key.

**Comment by agmansi970** [comment]
React  core ui CDatatable tableFilter is not working and showing No filtering results
