### ISSUE TITLE
[CDataTable] add class to row at rutime

### ISSUE THREAD

**Issue by rocchidavide** [coreui/coreui-vue#91]
I need to add a class to a CDataTable row programmatically, something like:

```
this.items.forEach((item) => {
     item['_classes'] = 'bg-warning'
})
```

This code works only when I interact with the rows (for example, clicking on the toggle details button). Do I have to do something else?

Thank you

**Comment by woothu** [comment]
Hi! It's possible, but you have to make sure that changed items are passed to CDataTable. If you have problems with that please make minimal repro example with code sandbox based on this template showing your code: https://codesandbox.io/s/coreui-vue-cdatatable-tbhfm?file=/src/App.vue

**Comment by rocchidavide** [comment]
First of all thank you for your quick response! 
I have some doubts about how to pass changed items to CDataTable... Do I have to replace them, or replace all items?
I create this sandbox: https://codesandbox.io/s/coreui-vue-cdatatable-h0k7e?file=/src/App.vue

**Comment by woothu** [comment]
Your solution is working but I would highly suggest not making direct computation on items since it will make it prone to errors.

https://codesandbox.io/s/coreui-vue-cdatatable-ebjr2?file=/src/App.vue

P.S. Notice that this issue is purely connected to Vue framework, not CoreUI Vue

**Comment by rocchidavide** [comment]
Thank you very much for your help, I appreciated it :)
