### ISSUE TITLE
How to capture event on <Cmodal click Ok or cancel ?

### ISSUE THREAD

**Issue by yaswanthkoneri** [coreui/coreui-vue#92]

**Comment by woothu** [comment]
https://coreui.io/vue/docs/components/modal.html

**Comment by yaswanthkoneri** [comment]
@woothu Documentation is not clear

**Comment by woothu** [comment]
There is one event firing if the modal is closed "update:show". It doesn't specify how it was closed, so you need to create own 'footer' slot with buttons that have custom events.

**Comment by bettafish15** [comment]
then what is the point of the OK and Cancel button of the CModal? it doesnt make any sense. If it has buttons then it has to register events for them .

**Comment by woothu** [comment]
@bettafish15 good point

**Comment by woothu** [comment]
In 3.1.1 version there is the third argument `accept` in the `update:show` event, it is true only if 'ok' button is clicked.

**Comment by cocobienak** [comment]
how to use that,, can you give the example code.

**Comment by bitbandit01** [comment]
I see the fix but I still have no idea how to access the accept variable from the .sync event.  Please update the documentation with an example or at least provide one here.

**Comment by geri777** [comment]
For the OK button this is fine. But I also need to distinguish between the [Cancel] button and [X].
