### ISSUE TITLE
How to reset CSelect value?

### ISSUE THREAD

**Issue by rocchidavide** [coreui/coreui-vue#93]
I'm using CSelect value with placeholder prop like this:

```
<CSelect
           label="Price list"
           :options="priceLists"
           placeholder="Select..."
           :value.sync="priceListId"
/>
```

The problem is that placeholder is shown only until a value is selected.
How can I reset selected value?

**Comment by woothu** [comment]
Set value to null/ some value that is not taken by options.

**Comment by rocchidavide** [comment]
If is set value to `null`, `priceListId` is set as the entire object (`{value: null, label: 'Select...'}`), not `null`... is it normal?

I do this:

```
this.priceLists = [{value: null, label: 'Select...'}]
              
response.data.results.forEach((priceList) => {
      this.priceLists.push({
             value: priceList.id,
             label: priceList.name,
      })
})
```

**Comment by woothu** [comment]
I have made an example showing how it works, please make a fork with your case if you need more guidance: https://codesandbox.io/s/coreui-vue-select-t37uh?file=/src/App.vue

**Comment by rocchidavide** [comment]
Ok, I tried your sandbox and I saw that the problem is @coreui/vui version: I have 3.0.6 and switching it in the sandbox the problem is reproduced.

**Comment by woothu** [comment]
Its not template you have to upgrade, but library `coreui-vue`
