### ISSUE TITLE
CDataTable small style

### ISSUE THREAD

**Issue by gabryray** [coreui/coreui-vue#94]
I am experimenting with the CDataTable component but I am having problems setting the "small" style. It appears that it is not being applied.

I also tried the example: "**_coreui-free-vue-admin-template_**" and in fact even there it doesn't seem to apply the small style.

I have configure the component like this:

`                <CDataTable
                  striped
                  small
                  :fields="fields"
                  :items="items"
                />`

the striped style is correctly applied but no the small.

I'm using Chrome on Windows 10.

**Comment by woothu** [comment]
Hi! Thank you for the report!

The docs considering this prop are incorrect. Please use size="sm" instead. 

Btw. Chrome Vue Devtools extension is great to check component state and props
