### ISSUE TITLE
CSelect not working in IE/Edge

### ISSUE THREAD

**Issue by ariccy** [coreui/coreui-vue#97]
### Vue.js version 
2.6.11
### coreui-vue version
3.0.8
### The issue
@input for select element is not supported by IE/Edge.
[IE11 <select @input="..."> not firing on selection change](https://github.com/vuejs/vue/issues/4701).

Vue.js uses change event for v-model on select element internally for this issue.
[https://vuejs.org/v2/guide/forms.html](url)

CSelect should also use @change or v-model on select for IE/Edge support.

**Comment by woothu** [comment]
Supported events of components are described in the documentation.

v-model is only shortcut syntax for @input and :value

This library is using '.sync' modifiers

**Comment by ariccy** [comment]
I am refering to the implementation, not the api.
[https://github.com/coreui/coreui-vue/blob/master/src/components/form/CSelect.vue#L22](url)

The @update:value event is never emitted for **CSelect** on IE/Edge because only @change is support on **select**.

**Comment by woothu** [comment]
I will check that, thank you for the report

**Comment by woothu** [comment]
fixed in 3.0.11 version

**Comment by ariccy** [comment]
Hi,
Can you publish the fixed version to npm?
Thank you.

**Comment by xidedix** [comment]
@ariccy 3.0.11 published - thanks for patience
