### ISSUE TITLE
CInputCheckbox custom do not 'checking'

### ISSUE THREAD

**Issue by yukiokun057** [coreui/coreui-vue#98]
Hello,

I want to make a table with checkbox element. I need to check item in two ways. Clicking on a row and checking a checkbox. I've notice that in custom mode checkbox do not 'checking'.

Take a look, please
https://codesandbox.io/s/cinputcheckbox-custom-bug-lfx2t

- Operating system and version (Windows 10)
- Browser and version (Opera 68.0.3618.125)

**Comment by woothu** [comment]
Scoped slots cannot be used to update "items"

this way it works: https://codesandbox.io/s/cinputcheckbox-custom-bug-vqt6d?file=/src/App.vue
