### ISSUE TITLE
How to reset CDataTable column filters?

### ISSUE THREAD

**Issue by rocchidavide** [coreui/coreui-vue#99]
How can I empty column filters inputs? My idea is to make a button outside the table that resets filter values, but I can't understand how to change filter values programmatically.

Thanks

**Comment by woothu** [comment]
We are planning to introduce such a feature in the next major release. Probably there will be an optional clear icon available next to the 'itemsPerPageSelect'

Solution for now:
https://codesandbox.io/s/cdatatable-clear-filters-eprwh?file=/src/App.vue
